-- Dados iniciais equivalentes a app.seed; sem credenciais.
SET NAMES utf8mb4;
INSERT IGNORE INTO permissions (code) VALUES ('cash.close');
INSERT IGNORE INTO permissions (code) VALUES ('cash.deposit');
INSERT IGNORE INTO permissions (code) VALUES ('cash.open');
INSERT IGNORE INTO permissions (code) VALUES ('cash.withdraw');
INSERT IGNORE INTO permissions (code) VALUES ('customers.create');
INSERT IGNORE INTO permissions (code) VALUES ('customers.read');
INSERT IGNORE INTO permissions (code) VALUES ('customers.update');
INSERT IGNORE INTO permissions (code) VALUES ('inventory.adjust');
INSERT IGNORE INTO permissions (code) VALUES ('inventory.read');
INSERT IGNORE INTO permissions (code) VALUES ('products.create');
INSERT IGNORE INTO permissions (code) VALUES ('products.delete');
INSERT IGNORE INTO permissions (code) VALUES ('products.read');
INSERT IGNORE INTO permissions (code) VALUES ('products.update');
INSERT IGNORE INTO permissions (code) VALUES ('reports.financial');
INSERT IGNORE INTO permissions (code) VALUES ('reports.read');
INSERT IGNORE INTO permissions (code) VALUES ('sales.cancel');
INSERT IGNORE INTO permissions (code) VALUES ('sales.create');
INSERT IGNORE INTO permissions (code) VALUES ('sales.discount');
INSERT IGNORE INTO permissions (code) VALUES ('sales.read');
INSERT IGNORE INTO permissions (code) VALUES ('settings.read');
INSERT IGNORE INTO permissions (code) VALUES ('settings.update');
INSERT IGNORE INTO permissions (code) VALUES ('users.create');
INSERT IGNORE INTO permissions (code) VALUES ('users.disable');
INSERT IGNORE INTO permissions (code) VALUES ('users.read');
INSERT IGNORE INTO permissions (code) VALUES ('users.update');
INSERT IGNORE INTO roles (name) VALUES ('Administrador');
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.close' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.deposit' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.open' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.withdraw' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='customers.create' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='customers.read' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='customers.update' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='inventory.adjust' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='inventory.read' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.create' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.delete' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.read' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.update' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='reports.financial' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='reports.read' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.cancel' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.create' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.discount' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.read' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='settings.read' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='settings.update' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='users.create' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='users.disable' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='users.read' WHERE r.name='Administrador';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='users.update' WHERE r.name='Administrador';
INSERT IGNORE INTO roles (name) VALUES ('Gerente');
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.close' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.deposit' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.open' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.withdraw' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='customers.create' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='customers.read' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='customers.update' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='inventory.adjust' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='inventory.read' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.create' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.delete' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.read' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.update' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='reports.financial' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='reports.read' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.cancel' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.create' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.discount' WHERE r.name='Gerente';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.read' WHERE r.name='Gerente';
INSERT IGNORE INTO roles (name) VALUES ('Vendedor');
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.read' WHERE r.name='Vendedor';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='customers.read' WHERE r.name='Vendedor';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.read' WHERE r.name='Vendedor';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='sales.create' WHERE r.name='Vendedor';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.open' WHERE r.name='Vendedor';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='cash.close' WHERE r.name='Vendedor';
INSERT IGNORE INTO roles (name) VALUES ('Consulta');
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='products.read' WHERE r.name='Consulta';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='inventory.read' WHERE r.name='Consulta';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code='reports.read' WHERE r.name='Consulta';
