#include "cash.hpp"
#include "module_policy.hpp"
#include "money.hpp"
#include "finance_input.hpp"
#include "erp_fonts.h"
#include "esp_heap_caps.h"
#include "esp_random.h"
#include "esp_log.h"
#include "cJSON.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include <atomic>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <new>
#include <string>

namespace tab5 { namespace {
enum class Mode {Home,Form,Review,Sessions,Session,Movements,Accounts,Account,Categories,Settlements,Result,Pending,Blocked};
enum class Action {Init,Current,Open,Deposit,Withdraw,Close,Sessions,Session,Movements,Receivables,Payables,Accounts,Account,Categories,SelectCategory,NewAccount,NewCategory,Settle,Settlements,Review,Send,Retry,Resolve};
struct Row {int id;char label[1300];};
struct State {unsigned serial,count,next;int user,session,selected_session,last,account,version,category;bool busy,pending,opened,payable;Mode mode;Action operation;Row rows[8];char message[350],summary[8192],expected[40],remaining[40],description[961],category_name[321];};
struct Command {Action action;unsigned generation,after;int id,method;bool only_open;char amount[40],reason[961],date[24],contact[24],from[24],to[24];};
struct Workspace {State state,working,draw;Command command;char permissions[2048],response[16385],body[4097],pending[4097];};
Workspace* w;SemaphoreHandle_t mutex;QueueHandle_t queue;std::atomic<unsigned> generation{0};std::atomic<bool> visible{false};unsigned drawn;
lv_obj_t *root,*title,*notice,*list,*panel,*summary,*rows[8],*buttons[8],*inputs[4],*labels[4],*method,*method_label,*range_from,*range_to,*only_open,*keyboard;
lv_group_t* group;void(*home_callback)();
constexpr const char* methods[]={"cash","pix","debit","credit","transfer","other"};
const char* text(cJSON* data,const char* key){auto* v=cJSON_GetObjectItemCaseSensitive(data,key);return cJSON_IsString(v)?v->valuestring:"";}
int number(cJSON* data,const char* key){auto* v=cJSON_GetObjectItemCaseSensitive(data,key);return cJSON_IsNumber(v)?v->valueint:0;}
const char* kind(){return w->working.payable?"payable":"receivable";}
const char* operation(Action a){switch(a){case Action::Open:return "Abrir caixa";case Action::Deposit:return "Suprimento";case Action::Withdraw:return "Sangria";case Action::Close:return "Fechar caixa";case Action::NewAccount:return "Cadastrar conta";case Action::NewCategory:return "Cadastrar categoria";default:return "Registrar baixa";}}
const char* method_name(const char* m){if(!strcmp(m,"cash"))return "Dinheiro";if(!strcmp(m,"pix"))return "Pix";if(!strcmp(m,"debit"))return "Débito";if(!strcmp(m,"credit"))return "Crédito";if(!strcmp(m,"transfer"))return "Transferência";return "Outros";}
const char* movement_name(const char* k){if(!strcmp(k,"sale"))return "Venda";if(!strcmp(k,"sale_reversal"))return "Estorno gerencial";if(!strcmp(k,"deposit"))return "Suprimento";if(!strcmp(k,"withdraw"))return "Sangria";return "Baixa de conta";}
void publish(const Command& cmd,const char* message){xSemaphoreTake(mutex,portMAX_DELAY);if(cmd.generation==generation){w->working.busy=false;snprintf(w->working.message,sizeof(w->working.message),"%s",message);w->working.serial=w->state.serial+1;w->state=w->working;}xSemaphoreGive(mutex);}
void enqueue(Action action,int id=0,unsigned after=0){if(!visible)return;Command cmd{};cmd.action=action;cmd.generation=generation;cmd.id=id;cmd.after=after;cmd.method=lv_dropdown_get_selected(method);cmd.only_open=lv_obj_has_state(only_open,LV_STATE_CHECKED);snprintf(cmd.amount,sizeof(cmd.amount),"%s",lv_textarea_get_text(inputs[0]));snprintf(cmd.reason,sizeof(cmd.reason),"%s",lv_textarea_get_text(inputs[1]));snprintf(cmd.date,sizeof(cmd.date),"%s",lv_textarea_get_text(inputs[2]));snprintf(cmd.contact,sizeof(cmd.contact),"%s",lv_textarea_get_text(inputs[3]));snprintf(cmd.from,sizeof(cmd.from),"%s",lv_textarea_get_text(range_from));snprintf(cmd.to,sizeof(cmd.to),"%s",lv_textarea_get_text(range_to));xSemaphoreTake(mutex,portMAX_DELAY);if(!w->state.busy&&xQueueSend(queue,&cmd,0)==pdTRUE){w->state.busy=true;++w->state.serial;snprintf(w->state.message,sizeof(w->state.message),"Aguarde...");}xSemaphoreGive(mutex);}
void keyboard_target(lv_event_t* e){lv_keyboard_set_textarea(keyboard,lv_event_get_target_obj(e));if(lv_event_get_code(e)==LV_EVENT_CLICKED)lv_obj_remove_flag(keyboard,LV_OBJ_FLAG_HIDDEN);}
void key_event(lv_event_t* e){auto key=lv_event_get_key(e);if(key==LV_KEY_ESC){if(!lv_obj_has_flag(keyboard,LV_OBJ_FLAG_HIDDEN))lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);else{cash_hide();home_callback();}}else if(key==LV_KEY_UP)lv_group_focus_prev(group);else if(key==LV_KEY_DOWN)lv_group_focus_next(group);}
void row_event(lv_event_t* e){auto mode=w->draw.mode;if(mode==Mode::Categories){lv_textarea_set_text(inputs[0],"0");lv_textarea_set_text(inputs[1],"");lv_textarea_set_text(inputs[2],"");lv_textarea_set_text(inputs[3],"");}Action a=mode==Mode::Sessions?Action::Session:mode==Mode::Accounts?Action::Account:mode==Mode::Categories?Action::SelectCategory:Action::Current;enqueue(a,static_cast<int>(reinterpret_cast<intptr_t>(lv_event_get_user_data(e))));}
void click(lv_event_t* e){unsigned i=reinterpret_cast<uintptr_t>(lv_event_get_user_data(e));if(i==7){cash_hide();home_callback();return;}auto& s=w->draw;if(s.busy)return;
    if(s.mode==Mode::Home){if(i==0){lv_textarea_set_text(inputs[0],"0");lv_textarea_set_text(inputs[1],"");enqueue(s.opened?Action::Close:Action::Open);}if(i==1||i==2){lv_textarea_set_text(inputs[0],"0");lv_textarea_set_text(inputs[1],"");enqueue(i==1?Action::Deposit:Action::Withdraw);}if(i==3)enqueue(Action::Sessions);if(i==4)enqueue(Action::Receivables);if(i==5)enqueue(Action::Payables);if(i==6)enqueue(Action::Current);}
    else if(s.mode==Mode::Form){if(i==0)enqueue(Action::Review);if(i==1)enqueue(Action::Current);}
    else if(s.mode==Mode::Review){if(i==0)enqueue(Action::Send);if(i==1)enqueue(Action::Current);}
    else if(s.mode==Mode::Pending){if(i==0)enqueue(Action::Retry);if(i==1)enqueue(Action::Resolve);}
    else if(s.mode==Mode::Sessions){if(i==0)enqueue(Action::Sessions,0,s.next);if(i==1)enqueue(Action::Current);}
    else if(s.mode==Mode::Session){if(i==0)enqueue(Action::Movements);if(i==1)enqueue(Action::Sessions);}
    else if(s.mode==Mode::Movements){if(i==0)enqueue(Action::Movements,0,s.next);if(i==1)enqueue(Action::Session,s.selected_session);}
    else if(s.mode==Mode::Accounts){if(i==0)enqueue(Action::Accounts);if(i==1)enqueue(Action::Accounts,0,s.next);if(i==2)enqueue(Action::Categories);if(i==3)enqueue(Action::Current);}
    else if(s.mode==Mode::Account){if(i==0){lv_textarea_set_text(inputs[0],s.remaining);lv_textarea_set_text(inputs[1],"");enqueue(Action::Settle);}if(i==1)enqueue(Action::Settlements);if(i==2)enqueue(Action::Accounts);}
    else if(s.mode==Mode::Categories){if(i==0){lv_textarea_set_text(inputs[1],"");enqueue(Action::NewCategory);}if(i==1)enqueue(Action::Categories,0,s.next);if(i==2)enqueue(Action::Accounts);}
    else if(s.mode==Mode::Settlements){if(i==0)enqueue(Action::Settlements,0,s.next);if(i==1)enqueue(Action::Account,s.account);}
    else if(s.mode==Mode::Result){if(i==0)enqueue(Action::Current);}
}
void render(lv_timer_t*){if(!visible)return;xSemaphoreTake(mutex,portMAX_DELAY);w->draw=w->state;xSemaphoreGive(mutex);auto& s=w->draw;if(s.serial==drawn)return;drawn=s.serial;lv_group_remove_all_objs(group);lv_group_set_default(group);for(auto* indev=lv_indev_get_next(nullptr);indev;indev=lv_indev_get_next(indev))if(lv_indev_get_type(indev)==LV_INDEV_TYPE_KEYPAD)lv_indev_set_group(indev,group);
    lv_label_set_text(title,s.mode==Mode::Accounts?(s.payable?"Financeiro | Contas a pagar":"Financeiro | Contas a receber"):s.mode==Mode::Categories?"Financeiro | Escolha uma categoria":s.mode==Mode::Form?operation(s.operation):s.mode==Mode::Review?"Caixa / Financeiro | Confirmar operação":s.mode==Mode::Pending?"Caixa / Financeiro | Tentativa pendente":"Caixa / Financeiro");lv_label_set_text(notice,s.message);
    bool listing=s.mode==Mode::Sessions||s.mode==Mode::Movements||s.mode==Mode::Accounts||s.mode==Mode::Categories||s.mode==Mode::Settlements;bool form=s.mode==Mode::Form;bool account_form=form&&s.operation==Action::NewAccount;bool category_form=form&&s.operation==Action::NewCategory;bool settlement=form&&s.operation==Action::Settle;
    for(unsigned i=0;i<4;++i){bool show=form&&(i<2||account_form)&&!(category_form&&i==0);for(auto* o:{inputs[i],labels[i]}){if(show)lv_obj_remove_flag(o,LV_OBJ_FLAG_HIDDEN);else lv_obj_add_flag(o,LV_OBJ_FLAG_HIDDEN);}if(show){lv_group_add_obj(group,inputs[i]);if(s.busy)lv_obj_add_state(inputs[i],LV_STATE_DISABLED);else lv_obj_remove_state(inputs[i],LV_STATE_DISABLED);}}
    lv_label_set_text(labels[0],s.operation==Action::Close?"Dinheiro contado (não inclui Pix/cartões)":"Valor (até 2 casas decimais)");lv_label_set_text(labels[1],account_form?"Descrição da conta":category_form?"Nome da categoria":"Justificativa / observação obrigatória");lv_label_set_text(labels[2],"Vencimento (AAAA-MM-DD)");lv_label_set_text(labels[3],"ID cliente/fornecedor (opcional)");
    for(auto* o:{method,method_label}){if(settlement)lv_obj_remove_flag(o,LV_OBJ_FLAG_HIDDEN);else lv_obj_add_flag(o,LV_OBJ_FLAG_HIDDEN);}if(settlement)lv_group_add_obj(group,method);
    for(auto* o:{range_from,range_to,only_open}){if(s.mode==Mode::Accounts){lv_obj_remove_flag(o,LV_OBJ_FLAG_HIDDEN);lv_group_add_obj(group,o);}else lv_obj_add_flag(o,LV_OBJ_FLAG_HIDDEN);}
    if(listing){lv_obj_remove_flag(list,LV_OBJ_FLAG_HIDDEN);lv_obj_add_flag(panel,LV_OBJ_FLAG_HIDDEN);}else{lv_obj_add_flag(list,LV_OBJ_FLAG_HIDDEN);lv_obj_remove_flag(panel,LV_OBJ_FLAG_HIDDEN);lv_obj_set_height(panel,form?130:430);lv_label_set_text(summary,s.summary);}
    for(unsigned i=0;i<8;++i){lv_obj_remove_event_cb(rows[i],row_event);if(listing&&i<s.count){lv_obj_remove_flag(rows[i],LV_OBJ_FLAG_HIDDEN);lv_label_set_text(lv_obj_get_child(rows[i],0),s.rows[i].label);if(s.mode==Mode::Sessions||s.mode==Mode::Accounts||s.mode==Mode::Categories){lv_obj_add_event_cb(rows[i],row_event,LV_EVENT_CLICKED,reinterpret_cast<void*>(static_cast<intptr_t>(s.rows[i].id)));lv_group_add_obj(group,rows[i]);}}else lv_obj_add_flag(rows[i],LV_OBJ_FLAG_HIDDEN);}
    const char* names[8]={"","","","","","","","Menu"};bool financial=has_module_permission(w->permissions,"reports.financial");bool deposit=has_module_permission(w->permissions,"cash.deposit"),withdraw=has_module_permission(w->permissions,"cash.withdraw");
    if(s.mode==Mode::Home){if(has_module_permission(w->permissions,s.opened?"cash.close":"cash.open"))names[0]=s.opened?"Fechar caixa":"Abrir caixa";if(s.opened&&deposit)names[1]="Suprimento";if(s.opened&&withdraw)names[2]="Sangria";names[3]="Histórico de caixas";if(financial){names[4]="Contas a receber";names[5]="Contas a pagar";}names[6]="Atualizar";}
    if(form){names[0]="Revisar operação";names[1]="Cancelar";}if(s.mode==Mode::Review){names[0]="Confirmar e gravar";names[1]="Cancelar";}if(s.mode==Mode::Pending){names[0]="Reenviar";names[1]="Resolver tentativa";}
    if(listing){names[0]="Próxima";names[1]="Voltar";}if(s.mode==Mode::Session){names[0]="Movimentações";names[1]="Histórico";}if(s.mode==Mode::Accounts){names[0]="Pesquisar / primeira";names[1]="Próxima";if(s.payable?withdraw:deposit)names[2]="Cadastrar conta";names[3]="Voltar ao caixa";}if(s.mode==Mode::Account){if(s.opened&&(s.payable?withdraw:deposit)&&strcmp(s.remaining,"0.00"))names[0]="Registrar baixa";names[1]="Histórico de baixas";names[2]="Voltar";}if(s.mode==Mode::Categories){if(s.payable?withdraw:deposit)names[0]="Nova categoria";names[1]="Próxima";names[2]="Voltar";}if(s.mode==Mode::Result)names[0]="Voltar ao caixa";
    for(unsigned i=0;i<8;++i){lv_label_set_text(lv_obj_get_child(buttons[i],0),names[i]);lv_obj_center(lv_obj_get_child(buttons[i],0));if(*names[i]){lv_obj_remove_flag(buttons[i],LV_OBJ_FLAG_HIDDEN);lv_group_add_obj(group,buttons[i]);}else lv_obj_add_flag(buttons[i],LV_OBJ_FLAG_HIDDEN);bool next=(s.mode==Mode::Accounts||s.mode==Mode::Categories)?i==1:listing&&i==0;if((s.busy&&i!=7)||(next&&!s.next))lv_obj_add_state(buttons[i],LV_STATE_DISABLED);else lv_obj_remove_state(buttons[i],LV_STATE_DISABLED);}
    static Mode previous=Mode::Blocked;if(previous!=s.mode||s.busy)lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);previous=s.mode;
}
void show_session(cJSON* row,bool home){auto& s=w->working;s.mode=home?Mode::Home:Mode::Session;if(!row||cJSON_IsNull(row)){s.opened=false;s.session=0;s.last=0;snprintf(s.summary,sizeof(s.summary),"Nenhum caixa aberto neste operador/terminal.\n\nAbra o caixa com o fundo inicial em dinheiro antes de concluir vendas ou registrar baixas.\n\nSuprimento acrescenta dinheiro; sangria retira dinheiro.\nContas a receber/pagar são compromissos separados dos pagamentos de vendas.");return;}if(home){s.session=number(row,"id");s.opened=!strcmp(text(row,"status"),"open");s.last=number(row,"last_movement_id");snprintf(s.expected,sizeof(s.expected),"%s",text(row,"expected_cash"));}s.selected_session=number(row,"id");auto* m=cJSON_GetObjectItemCaseSensitive(row,"by_method");snprintf(s.summary,sizeof(s.summary),"Caixa %d | %s | Operador %d\nAbertura %s | Encerramento %s\n\nFundo inicial: R$ %s | Vendas líquidas: R$ %s\nSuprimentos: R$ %s | Sangrias: R$ %s\nDinheiro movimentado: R$ %s | Pix: R$ %s\nDébito: R$ %s | Crédito: R$ %s\nTransferência: R$ %s | Outros: R$ %s\n\nDINHEIRO ESPERADO: R$ %s\nContado: %s | Diferença: %s\nObservação: %s\nFechamento: %s",number(row,"id"),!strcmp(text(row,"status"),"open")?"Aberto":"Fechado",number(row,"operator_id"),text(row,"created_at"),text(row,"closed_at"),text(row,"opening"),text(row,"sales_total"),text(row,"deposits"),text(row,"withdrawals"),text(m,"cash"),text(m,"pix"),text(m,"debit"),text(m,"credit"),text(m,"transfer"),text(m,"other"),text(row,"expected_cash"),text(row,"counted"),text(row,"difference"),text(row,"note"),text(row,"close_reason"));}
const char* failure(int code,cJSON* data){const char* msg=text(cJSON_GetObjectItemCaseSensitive(data,"error"),"message");return *msg?msg:code<=0?"Sem resposta da API. Confira a conexão.":"Operação recusada. Confira os campos e permissões.";}
bool valid_path(const char* p){for(auto* v:{"/api/v1/finance/cash/open","/api/v1/finance/cash/movements","/api/v1/finance/cash/close","/api/v1/finance/categories","/api/v1/finance/accounts","/api/v1/finance/settlements"})if(!strcmp(p,v))return true;return false;}
} // namespace

void cash_create(lv_display_t* display,void(*home)()){
    void* memory=heap_caps_calloc(1,sizeof(Workspace),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);if(!memory){ESP_LOGE("cash","PSRAM indisponível");return;}w=new(memory)Workspace{};mutex=xSemaphoreCreateMutex();auto* storage=static_cast<uint8_t*>(heap_caps_malloc(sizeof(Command),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT));static StaticQueue_t control;queue=xQueueCreateStatic(1,sizeof(Command),storage,&control);home_callback=home;group=lv_group_create();
    root=lv_obj_create(lv_display_get_screen_active(display));lv_obj_set_size(root,1280,720);lv_obj_set_style_pad_all(root,10,0);lv_obj_set_style_text_font(root,&erp_font_pt_20,0);lv_obj_remove_flag(root,LV_OBJ_FLAG_SCROLLABLE);title=lv_label_create(root);lv_obj_set_pos(title,8,4);lv_obj_set_style_text_font(title,&erp_font_pt_28,0);notice=lv_label_create(root);lv_obj_set_pos(notice,8,45);lv_obj_set_width(notice,1200);lv_label_set_long_mode(notice,LV_LABEL_LONG_DOT);
    list=lv_obj_create(root);lv_obj_set_pos(list,8,160);lv_obj_set_size(list,1220,360);for(unsigned i=0;i<8;++i){rows[i]=lv_button_create(list);lv_obj_set_pos(rows[i],0,i*96);lv_obj_set_size(rows[i],1165,92);auto* label=lv_label_create(rows[i]);lv_obj_set_width(label,1120);lv_label_set_long_mode(label,LV_LABEL_LONG_DOT);lv_obj_center(label);lv_obj_add_event_cb(rows[i],key_event,LV_EVENT_KEY,nullptr);}
    panel=lv_obj_create(root);lv_obj_set_pos(panel,8,88);lv_obj_set_size(panel,1220,430);summary=lv_label_create(panel);lv_obj_set_width(summary,1165);lv_label_set_long_mode(summary,LV_LABEL_LONG_WRAP);
    for(unsigned i=0;i<4;++i){labels[i]=lv_label_create(root);inputs[i]=lv_textarea_create(root);lv_textarea_set_one_line(inputs[i],true);lv_obj_set_size(inputs[i],i==1?1220:580,48);lv_obj_set_pos(labels[i],8+(i==3?622:0),i==0?232:i==1?324:420);lv_obj_set_pos(inputs[i],8+(i==3?622:0),i==0?262:i==1?354:450);lv_textarea_set_max_length(inputs[i],i==1?240:i==0?30:20);lv_obj_add_event_cb(inputs[i],keyboard_target,LV_EVENT_FOCUSED,nullptr);lv_obj_add_event_cb(inputs[i],keyboard_target,LV_EVENT_CLICKED,nullptr);lv_obj_add_event_cb(inputs[i],key_event,LV_EVENT_KEY,nullptr);}
    method_label=lv_label_create(root);lv_obj_set_pos(method_label,630,232);lv_label_set_text(method_label,"Forma de pagamento da baixa");method=lv_dropdown_create(root);lv_obj_set_pos(method,630,262);lv_obj_set_size(method,580,48);lv_dropdown_set_options(method,"Dinheiro\nPix\nDébito\nCrédito\nTransferência\nOutros");lv_obj_add_event_cb(method,key_event,LV_EVENT_KEY,nullptr);
    range_from=lv_textarea_create(root);range_to=lv_textarea_create(root);unsigned index=0;for(auto* object:{range_from,range_to}){lv_obj_set_pos(object,8+(index++)*420,96);lv_obj_set_size(object,400,48);lv_textarea_set_one_line(object,true);lv_textarea_set_max_length(object,10);lv_textarea_set_placeholder_text(object,index==1?"Vencimento desde AAAA-MM-DD":"Vencimento até AAAA-MM-DD");lv_obj_add_event_cb(object,keyboard_target,LV_EVENT_FOCUSED,nullptr);lv_obj_add_event_cb(object,keyboard_target,LV_EVENT_CLICKED,nullptr);lv_obj_add_event_cb(object,key_event,LV_EVENT_KEY,nullptr);}only_open=lv_checkbox_create(root);lv_obj_set_pos(only_open,880,107);lv_checkbox_set_text(only_open,"Somente em aberto");
    for(unsigned i=0;i<8;++i){buttons[i]=lv_button_create(root);lv_obj_set_pos(buttons[i],8+(i%4)*306,542+(i/4)*58);lv_obj_set_size(buttons[i],294,50);lv_label_create(buttons[i]);lv_obj_add_event_cb(buttons[i],click,LV_EVENT_CLICKED,reinterpret_cast<void*>(static_cast<uintptr_t>(i)));lv_obj_add_event_cb(buttons[i],key_event,LV_EVENT_KEY,nullptr);}
    keyboard=lv_keyboard_create(root);lv_obj_set_pos(keyboard,8,450);lv_obj_set_size(keyboard,1220,240);for(auto event:{LV_EVENT_READY,LV_EVENT_CANCEL})lv_obj_add_event_cb(keyboard,[](lv_event_t*){lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);},event,nullptr);lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);lv_obj_add_flag(root,LV_OBJ_FLAG_HIDDEN);lv_timer_create(render,100,nullptr);
}
void cash_hide(){if(!w)return;visible=false;++generation;xQueueReset(queue);lv_obj_add_flag(root,LV_OBJ_FLAG_HIDDEN);xSemaphoreTake(mutex,portMAX_DELAY);memset(&w->state,0,sizeof(w->state));xSemaphoreGive(mutex);memset(&w->draw,0,sizeof(w->draw));for(auto* input:inputs)lv_textarea_set_text(input,"");for(auto* input:{range_from,range_to})lv_textarea_set_text(input,"");for(auto* row:rows)lv_label_set_text(lv_obj_get_child(row,0),"");lv_label_set_text(summary,"");lv_label_set_text(notice,"");}
void cash_open(const char* permissions,bool light){if(!w)return;snprintf(w->permissions,sizeof(w->permissions),"%s",permissions);drawn=0;auto fg=lv_color_hex(light?0x0f172a:0xf8fafc),bg=lv_color_hex(light?0xe2e8f0:0x334155);lv_obj_set_style_bg_color(root,lv_color_hex(light?0xf1f5f9:0x111827),0);lv_obj_set_style_text_color(root,fg,0);for(auto* object:{list,panel})lv_obj_set_style_bg_color(object,lv_color_hex(light?0xffffff:0x1e293b),0);for(auto* object:inputs){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}for(auto* object:{range_from,range_to,method}){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}auto* drop=lv_dropdown_get_list(method);if(drop){lv_obj_set_style_bg_color(drop,bg,0);lv_obj_set_style_text_color(drop,fg,0);lv_obj_set_style_text_font(drop,&erp_font_pt_20,0);}for(auto* object:rows){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}for(auto* object:buttons){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}lv_obj_set_style_bg_color(keyboard,bg,LV_PART_ITEMS);lv_obj_set_style_text_color(keyboard,fg,LV_PART_ITEMS);visible=true;lv_obj_remove_flag(root,LV_OBJ_FLAG_HIDDEN);enqueue(Action::Init);render(nullptr);}

bool cash_handle_next(const char* permissions,bool online,ProductTransport transport,SaleJournal journal){if(!w||xQueueReceive(queue,&w->command,0)!=pdTRUE)return false;const auto& cmd=w->command;if(cmd.generation!=generation)return true;xSemaphoreTake(mutex,portMAX_DELAY);w->working=w->state;xSemaphoreGive(mutex);auto& s=w->working;
    auto done=[&](const char* message){publish(cmd,message);return true;};if(!online)return done("Sem rede. Caixa e financeiro precisam da API disponível.");auto call=[&](const char* method,const char* path,const char* body){memset(w->response,0,sizeof(w->response));return transport(method,path,body,w->response,sizeof(w->response));};
    if(cmd.action==Action::Init){int code=call("GET","/api/v1/auth/me",nullptr);auto* data=cJSON_Parse(w->response);s.user=number(data,"id");cJSON_Delete(data);if(code!=200||!s.user)return done("Não foi possível confirmar a sessão.");int loaded=journal("load",s.user,w->pending,sizeof(w->pending));s.pending=loaded!=0;if(loaded!=0){s.mode=loaded>0?Mode::Pending:Mode::Blocked;snprintf(s.summary,sizeof(s.summary),"Tentativa protegida no microSD. Reenviar repete o pedido original; Resolver consulta o resultado ou encerra a chave antes de permitir nova operação.");return done(loaded>0?"Tentativa pendente recuperada. Resolva para continuar.":"Pendência protegida: use o operador, dispositivo e API originais; preserve o cartão.");}}
    if(s.pending&&cmd.action!=Action::Retry&&cmd.action!=Action::Resolve)return done("Resolva a operação financeira pendente antes de continuar.");
    if(cmd.action==Action::Open||cmd.action==Action::Deposit||cmd.action==Action::Withdraw||cmd.action==Action::Close||cmd.action==Action::NewCategory||cmd.action==Action::Settle||cmd.action==Action::SelectCategory){s.operation=cmd.action==Action::SelectCategory?Action::NewAccount:cmd.action;s.mode=Mode::Form;if(cmd.action==Action::SelectCategory){s.category=cmd.id;for(unsigned i=0;i<s.count;++i)if(s.rows[i].id==cmd.id)snprintf(s.category_name,sizeof(s.category_name),"%.320s",s.rows[i].label);}
        if((s.operation==Action::Close||s.operation==Action::Deposit||s.operation==Action::Withdraw||s.operation==Action::Settle)&&!s.opened){return done("Abra um caixa antes desta operação.");}
        if(s.operation==Action::Close&&journal("can-close",s.user,w->body,sizeof(w->body))!=1){s.mode=Mode::Home;return done("Resolva as pendências de Vendas/Estoque antes de fechar o caixa.");}snprintf(s.summary,sizeof(s.summary),"%s\n%s\n%s",operation(s.operation),s.operation==Action::Close?s.expected:s.operation==Action::Settle?s.description:s.operation==Action::NewAccount?s.category_name:"Informe o valor e a justificativa.",s.operation==Action::Close?"Dinheiro esperado acima. Conte somente dinheiro; Pix/cartões ficam separados.":s.operation==Action::Settle?"Baixa manual: confirme o recebimento/pagamento antes de registrar.":"Revise os dados antes de confirmar.");return done("Preencha os campos e toque Revisar operação.");}
    char path[300]{};const char* verb="GET";const char* body=nullptr;
    if(cmd.action==Action::Review){if(s.mode!=Mode::Form)return done("Abra o formulário antes de revisar.");int64_t amount=0;bool category=s.operation==Action::NewCategory;if(!category&&(!money::parse(cmd.amount,2,amount)||amount>99999999999999LL||((s.operation!=Action::Open&&s.operation!=Action::Close)&&amount==0)))return done("Informe valor válido, com até 2 casas decimais.");std::string reason=cmd.reason;auto first=reason.find_first_not_of(" \t\r\n");if(first==std::string::npos)return done("Informe texto com pelo menos 3 caracteres.");reason=reason.substr(first,reason.find_last_not_of(" \t\r\n")-first+1);unsigned characters=0;for(unsigned char c:reason){if(c<32)return done("Texto com caractere de controle inválido.");if((c&0xc0)!=0x80)++characters;}if(characters<3)return done("Informe texto com pelo menos 3 caracteres.");if(category&&characters>80)return done("Nome da categoria: máximo de 80 caracteres.");
        if(s.operation==Action::Close&&journal("can-close",s.user,w->body,sizeof(w->body))!=1)return done("Resolva as pendências de Vendas/Estoque antes de fechar o caixa.");
        if(s.operation==Action::NewAccount&&!valid_financial_date(cmd.date))return done("Vencimento inválido. Use uma data real em AAAA-MM-DD.");
        auto* payload=cJSON_CreateObject();char value[40];money::format(value,sizeof(value),amount);if(!category)cJSON_AddStringToObject(payload,"amount",value);
        const char* target="/api/v1/finance/cash/open";if(s.operation==Action::NewCategory){target="/api/v1/finance/categories";cJSON_AddStringToObject(payload,"kind",kind());cJSON_AddStringToObject(payload,"name",reason.c_str());}
        else if(s.operation==Action::NewAccount){target="/api/v1/finance/accounts";cJSON_AddStringToObject(payload,"kind",kind());cJSON_AddStringToObject(payload,"description",reason.c_str());cJSON_AddStringToObject(payload,"due_date",cmd.date);cJSON_AddNumberToObject(payload,"category_id",s.category);if(*cmd.contact){char* end;long id=strtol(cmd.contact,&end,10);if(*end||id<=0||id>2147483647){cJSON_Delete(payload);return done("Informe ID válido do cliente/fornecedor, ou deixe vazio.");}cJSON_AddNumberToObject(payload,"contact_id",id);}}
        else{cJSON_AddStringToObject(payload,"reason",reason.c_str());if(s.operation!=Action::Open)cJSON_AddNumberToObject(payload,"session_id",s.session);if(s.operation==Action::Deposit||s.operation==Action::Withdraw){target="/api/v1/finance/cash/movements";cJSON_AddStringToObject(payload,"kind",s.operation==Action::Deposit?"deposit":"withdraw");}if(s.operation==Action::Close){target="/api/v1/finance/cash/close";cJSON_AddNumberToObject(payload,"last_movement_id",s.last);}if(s.operation==Action::Settle){target="/api/v1/finance/settlements";cJSON_AddNumberToObject(payload,"account_id",s.account);cJSON_AddNumberToObject(payload,"version",s.version);cJSON_AddStringToObject(payload,"method",methods[cmd.method>=0&&cmd.method<6?cmd.method:0]);}}
        auto* envelope=cJSON_CreateObject();cJSON_AddStringToObject(envelope,"path",target);cJSON_AddItemToObject(envelope,"body",payload);char* raw=cJSON_PrintUnformatted(envelope);cJSON_Delete(envelope);if(!raw||strlen(raw)>=sizeof(w->body)){cJSON_free(raw);return done("Pedido excede limite de armazenamento.");}snprintf(w->body,sizeof(w->body),"%s",raw);cJSON_free(raw);s.mode=Mode::Review;
        char closing[180]{};if(s.operation==Action::Close){int64_t expected=0;if(!money::parse(s.expected,2,expected))return done("Consulte novamente o saldo do caixa.");int64_t delta=amount-expected;char value_difference[40];money::format(value_difference,sizeof(value_difference),delta<0?-delta:delta);snprintf(closing,sizeof(closing),"Esperado R$ %s | Diferença %sR$ %s",s.expected,delta<0?"-":"",value_difference);}
        snprintf(s.summary,sizeof(s.summary),"%s\n%s\n\nValor: R$ %s\n%s\n%s\n\n%s\n\nConfirme somente após conferir os dados. A API valida saldo, permissão e versão.",operation(s.operation),s.operation==Action::NewAccount?s.category_name:s.operation==Action::Settle?s.description:"",category?"não se aplica":value,s.operation==Action::Close?closing:s.operation==Action::Settle?method_name(methods[cmd.method>=0&&cmd.method<6?cmd.method:0]):"",s.operation==Action::NewAccount?cmd.date:"",reason.c_str());return done("Confira a operação antes de confirmar e gravar.");}
    if(cmd.action==Action::Send){if(s.mode!=Mode::Review||!*w->body)return done("Revise a operação antes de confirmar.");auto* request=cJSON_Parse(w->body);auto* payload=cJSON_GetObjectItemCaseSensitive(request,"body");if(!cJSON_IsObject(payload)){cJSON_Delete(request);return done("Pedido inválido.");}uint8_t random[16];esp_fill_random(random,sizeof(random));char key[33];for(unsigned i=0;i<16;++i)snprintf(key+2*i,3,"%02x",random[i]);cJSON_AddStringToObject(payload,"idempotency_key",key);char* raw=cJSON_PrintUnformatted(request);cJSON_Delete(request);if(!raw||strlen(raw)>=sizeof(w->pending)){cJSON_free(raw);return done("Não foi possível registrar a tentativa.");}snprintf(w->pending,sizeof(w->pending),"%s",raw);cJSON_free(raw);if(journal("save",s.user,w->pending,sizeof(w->pending))!=1)return done("Falha no microSD. Operação não enviada.");s.pending=true;s.mode=Mode::Pending;}
    if(cmd.action==Action::Send||cmd.action==Action::Retry||cmd.action==Action::Resolve){auto* pending=cJSON_Parse(w->pending);auto* payload=cJSON_GetObjectItemCaseSensitive(pending,"body");const char* key=text(payload,"idempotency_key"),*target=text(pending,"path");if(!valid_path(target)||strlen(key)<16||strlen(key)>64){cJSON_Delete(pending);return done("Registro pendente inválido. Preserve o cartão para recuperação.");}if(cmd.action==Action::Resolve)snprintf(path,sizeof(path),"/api/v1/finance/requests/%s/resolve",key);else{snprintf(path,sizeof(path),"%s",target);char* raw=cJSON_PrintUnformatted(payload);if(!raw||strlen(raw)>=sizeof(w->body)){cJSON_free(raw);cJSON_Delete(pending);return done("Registro pendente inválido.");}snprintf(w->body,sizeof(w->body),"%s",raw);cJSON_free(raw);body=w->body;}cJSON_Delete(pending);verb="POST";}
    else if(cmd.action==Action::Init||cmd.action==Action::Current)snprintf(path,sizeof(path),"/api/v1/finance/cash/current");
    else if(cmd.action==Action::Sessions)snprintf(path,sizeof(path),"/api/v1/finance/cash/sessions?limit=8&after_id=%u",cmd.after);
    else if(cmd.action==Action::Session)snprintf(path,sizeof(path),"/api/v1/finance/cash/sessions/%d",cmd.id?cmd.id:s.selected_session);
    else if(cmd.action==Action::Movements)snprintf(path,sizeof(path),"/api/v1/finance/cash/sessions/%d/movements?limit=8&after_id=%u",s.selected_session,cmd.after);
    else if(cmd.action==Action::Account)snprintf(path,sizeof(path),"/api/v1/finance/accounts/%d",cmd.id?cmd.id:s.account);
    else if(cmd.action==Action::Settlements)snprintf(path,sizeof(path),"/api/v1/finance/accounts/%d/settlements?limit=8&after_id=%u",s.account,cmd.after);
    else if(cmd.action==Action::Categories)snprintf(path,sizeof(path),"/api/v1/finance/categories?kind=%s&limit=8&after_id=%u",kind(),cmd.after);
    else{if(cmd.action==Action::Receivables||cmd.action==Action::Payables)s.payable=cmd.action==Action::Payables;std::string url=std::string("/api/v1/finance/accounts?kind=")+kind()+"&limit=8&after_id="+std::to_string(cmd.after)+"&only_open="+(cmd.only_open?"true":"false");auto encode=[](const char* input){std::string value;for(const unsigned char* p=reinterpret_cast<const unsigned char*>(input);*p;++p){char bytes[4];snprintf(bytes,sizeof(bytes),"%%%02X",*p);value+=bytes;}return value;};if(*cmd.from)url+="&from_date="+encode(cmd.from);if(*cmd.to)url+="&to_date="+encode(cmd.to);if(url.size()>=sizeof(path))return done("Filtros excedem limite.");snprintf(path,sizeof(path),"%s",url.c_str());}
    int code=call(verb,path,body);auto* data=cJSON_Parse(w->response);std::string message;
    if(code<200||code>=300){message=failure(code,data);if(s.pending){s.mode=Mode::Pending;snprintf(s.summary,sizeof(s.summary),"Resultado não confirmado. Reenviar mantém o pedido original. Resolver consulta o resultado ou encerra a chave na API antes de permitir nova operação.");}}
    else if(cmd.action==Action::Init||cmd.action==Action::Current){show_session(cJSON_GetObjectItemCaseSensitive(data,"session"),true);message="Caixa por operador e terminal. Valores conferidos pelo servidor.";}
    else if(cmd.action==Action::Session){show_session(data,false);message="Fechamentos preservam os totais registrados na contagem.";}
    else if(cmd.action==Action::Account){s.mode=Mode::Account;s.account=number(data,"id");s.version=number(data,"version");s.payable=!strcmp(text(data,"kind"),"payable");snprintf(s.remaining,sizeof(s.remaining),"%s",text(data,"remaining"));snprintf(s.description,sizeof(s.description),"%s",text(data,"description"));snprintf(s.summary,sizeof(s.summary),"Conta %d | %s\n%s\nCategoria: %s | Cliente/fornecedor ID %d\n\nVencimento: %s\nValor original: R$ %s\nBaixado: R$ %s\nSALDO: R$ %s\n\n%s\n\nBaixa manual exige caixa aberto e confirmação do pagamento/recebimento. Não integra bancos.",s.account,s.payable?"A pagar":"A receber",s.description,text(data,"category"),number(data,"contact_id"),text(data,"due_date"),text(data,"amount"),text(data,"paid"),s.remaining,!strcmp(s.remaining,"0.00")?"Conta quitada":"Conta com saldo pendente");message="Conta consultada na API. Baixas parciais preservam o histórico.";}
    else if(cmd.action==Action::Send||cmd.action==Action::Retry||cmd.action==Action::Resolve){const bool abandoned=cmd.action==Action::Resolve&&!strcmp(text(data,"state"),"abandoned");auto* result=cmd.action==Action::Resolve?cJSON_GetObjectItemCaseSensitive(data,"result"):data;if(!abandoned&&number(result,"id")<=0){message="Resposta inválida. Preserve a tentativa pendente.";}else if(journal("clear",s.user,w->pending,sizeof(w->pending))!=1){s.mode=Mode::Pending;message="Resultado confirmado. Resolva novamente para limpar o registro do cartão.";}else{s.pending=false;w->pending[0]=0;s.mode=Mode::Result;if(abandoned){snprintf(s.summary,sizeof(s.summary),"Tentativa encerrada na API.\n\nUm envio atrasado com esta chave não será aplicado. Consulte os dados novamente antes de gerar outra operação.");message="Tentativa encerrada; nenhum resultado comercial nesta chave.";}else if(*text(result,"expected_cash")){show_session(result,false);s.mode=Mode::Result;message="Resultado original confirmado. Atualize o caixa para consultar o saldo atual.";}else{snprintf(s.summary,sizeof(s.summary),"Operação confirmada na API\nRegistro ID %d\n\n%s\n%s\nValor: R$ %s\n\nConsulte o caixa e a conta para conferir os saldos atualizados.",number(result,"id"),text(result,"name"),text(result,"description"),text(result,"amount"));message="Operação concluída. Reenvio com a mesma chave não duplica registros.";}}}
    else{s.count=0;s.next=number(data,"next_id");s.mode=cmd.action==Action::Sessions?Mode::Sessions:cmd.action==Action::Movements?Mode::Movements:cmd.action==Action::Categories?Mode::Categories:cmd.action==Action::Settlements?Mode::Settlements:Mode::Accounts;cJSON* item;auto* items=cJSON_GetObjectItemCaseSensitive(data,"items");cJSON_ArrayForEach(item,items){if(s.count==8)break;auto& row=s.rows[s.count++];row.id=number(item,"id");if(s.mode==Mode::Sessions)snprintf(row.label,sizeof(row.label),"Caixa %d | %s | %s\nEsperado R$ %s | Contado %s | Diferença %s",row.id,!strcmp(text(item,"status"),"open")?"Aberto":"Fechado",text(item,"created_at"),text(item,"expected_cash"),text(item,"counted"),text(item,"difference"));else if(s.mode==Mode::Accounts)snprintf(row.label,sizeof(row.label),"ID %d | %s\nVencimento %s | Valor R$ %s | Saldo R$ %s | %s",row.id,text(item,"description"),text(item,"due_date"),text(item,"amount"),text(item,"remaining"),cJSON_IsTrue(cJSON_GetObjectItemCaseSensitive(item,"overdue"))?"Vencida":"");else if(s.mode==Mode::Categories)snprintf(row.label,sizeof(row.label),"%s",text(item,"name"));else snprintf(row.label,sizeof(row.label),"ID %d | %s | %s | R$ %s\n%s | Operador %d | %s",row.id,s.mode==Mode::Movements?movement_name(text(item,"kind")):"Baixa",method_name(text(item,"method")),text(item,"amount"),text(item,"created_at"),number(item,"operator_id"),text(item,"reason"));}message=s.mode==Mode::Categories?"Toque na categoria para cadastrar a conta; use Nova categoria se necessário.":"Consulta paginada na API. Toque em caixa/conta para abrir detalhes.";}
    cJSON_Delete(data);return done(message.c_str());
}
} // namespace tab5
