#include "inventory.hpp"
#include "module_policy.hpp"
#include "money.hpp"
#include "erp_fonts.h"
#include "esp_heap_caps.h"
#include "esp_random.h"
#include "esp_log.h"
#include "cJSON.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include <atomic>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <new>
#include <string>

namespace tab5 { namespace {
enum class Mode {List,Detail,Form,Review,Pending,History,Movement,Blocked};
enum class Action {Init,Browse,Get,Entry,Exit,Count,Review,Send,Retry,Resolve,History,Movement};
struct Product {int id,version;bool active,low;char name[481],sku[33],unit[9],stock[40],minimum[40],maximum[40];};
struct Row {int id;char label[900];};
struct State {unsigned serial,count,next,revision;int user;bool busy,pending;Mode mode;Action operation;Product product;Row rows[8];char message[350],summary[8192];};
struct Command {Action action;unsigned generation,after;int id;bool low,inactive;char query[481],quantity[32],reason[961];};
struct Workspace {State state,draw,working;Command command;char permissions[2048],response[16385],body[4097],pending[4097];};
Workspace* w;SemaphoreHandle_t mutex;QueueHandle_t queue;std::atomic<unsigned> generation{0};std::atomic<bool> visible{false};
lv_obj_t *root,*title,*notice,*query,*low,*inactive,*list,*rows[8],*panel,*summary,*quantity,*reason,*qty_label,*reason_label,*buttons[8],*keyboard;
lv_group_t* group;void(*home_callback)();unsigned drawn=0;
const char* text(cJSON* data,const char* key){auto* item=cJSON_GetObjectItemCaseSensitive(data,key);return cJSON_IsString(item)?item->valuestring:"";}
int number(cJSON* data,const char* key){auto* item=cJSON_GetObjectItemCaseSensitive(data,key);return cJSON_IsNumber(item)?item->valueint:0;}
const char* kind(Action action){return action==Action::Entry?"entry":action==Action::Exit?"exit":"adjustment";}
const char* operation(Action action){return action==Action::Entry?"Entrada":action==Action::Exit?"Saída":"Contagem / ajuste";}
const char* movement_kind(const char* value){if(!strcmp(value,"inventory_entry"))return "Entrada";if(!strcmp(value,"inventory_exit"))return "Saída";if(!strcmp(value,"inventory_adjustment"))return "Contagem";if(!strcmp(value,"sale"))return "Venda";if(!strcmp(value,"cancellation"))return "Cancelamento";if(!strcmp(value,"initial")||!strcmp(value,"opening"))return "Saldo inicial";return "Ajuste cadastral";}
void publish(const Command& cmd,const char* message){xSemaphoreTake(mutex,portMAX_DELAY);if(cmd.generation==generation){w->working.busy=false;snprintf(w->working.message,sizeof(w->working.message),"%s",message);w->working.serial=w->state.serial+1;w->state=w->working;}xSemaphoreGive(mutex);}
void enqueue(Action action,int id=0,unsigned after=0){if(!visible)return;Command cmd{};cmd.action=action;cmd.id=id;cmd.after=after;cmd.generation=generation;snprintf(cmd.query,sizeof(cmd.query),"%s",lv_textarea_get_text(query));snprintf(cmd.quantity,sizeof(cmd.quantity),"%s",lv_textarea_get_text(quantity));snprintf(cmd.reason,sizeof(cmd.reason),"%s",lv_textarea_get_text(reason));cmd.low=lv_obj_has_state(low,LV_STATE_CHECKED);cmd.inactive=lv_obj_has_state(inactive,LV_STATE_CHECKED);xSemaphoreTake(mutex,portMAX_DELAY);if(!w->state.busy&&xQueueSend(queue,&cmd,0)==pdTRUE){w->state.busy=true;++w->state.serial;snprintf(w->state.message,sizeof(w->state.message),"Aguarde...");}xSemaphoreGive(mutex);}
void keyboard_target(lv_event_t* event){lv_keyboard_set_textarea(keyboard,lv_event_get_target_obj(event));if(lv_event_get_code(event)==LV_EVENT_CLICKED)lv_obj_remove_flag(keyboard,LV_OBJ_FLAG_HIDDEN);}
void key_event(lv_event_t* event){auto key=lv_event_get_key(event);if(key==LV_KEY_ESC){if(!lv_obj_has_flag(keyboard,LV_OBJ_FLAG_HIDDEN))lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);else{inventory_hide();home_callback();}}else if(key==LV_KEY_UP)lv_group_focus_prev(group);else if(key==LV_KEY_DOWN)lv_group_focus_next(group);}
void row_event(lv_event_t* event){enqueue(w->draw.mode==Mode::History?Action::Movement:Action::Get,static_cast<int>(reinterpret_cast<intptr_t>(lv_event_get_user_data(event))));}
void click(lv_event_t* event){unsigned i=reinterpret_cast<uintptr_t>(lv_event_get_user_data(event));if(i==7){inventory_hide();home_callback();return;}auto& s=w->draw;if(s.busy)return;
    if(s.mode==Mode::List){if(i==0||i==2)enqueue(Action::Browse);if(i==1)enqueue(Action::Browse,0,s.next);}
    else if(s.mode==Mode::Detail){if(i<3){lv_textarea_set_text(quantity,i==2?s.product.stock:"0");lv_textarea_set_text(reason,"");enqueue(i==0?Action::Entry:i==1?Action::Exit:Action::Count);}if(i==3)enqueue(Action::History);if(i==4)enqueue(Action::Browse);}
    else if(s.mode==Mode::Form){if(i==0)enqueue(Action::Review);if(i==1)enqueue(Action::Get,s.product.id);}
    else if(s.mode==Mode::Review){if(i==0)enqueue(Action::Send);if(i==1)enqueue(Action::Get,s.product.id);}
    else if(s.mode==Mode::Pending){if(i==0)enqueue(Action::Retry);if(i==1)enqueue(Action::Resolve);}
    else if(s.mode==Mode::Movement){if(i==0)enqueue(Action::History);if(i==1)enqueue(Action::Get,s.product.id);}
    else if(s.mode==Mode::History){if(i==0)enqueue(Action::History,0,s.next);if(i==1)enqueue(Action::Get,s.product.id);}
}
void render(lv_timer_t*){if(!visible)return;xSemaphoreTake(mutex,portMAX_DELAY);w->draw=w->state;xSemaphoreGive(mutex);auto& s=w->draw;if(s.serial==drawn)return;drawn=s.serial;
    lv_group_remove_all_objs(group);lv_group_set_default(group);for(auto* input=lv_indev_get_next(nullptr);input;input=lv_indev_get_next(input))if(lv_indev_get_type(input)==LV_INDEV_TYPE_KEYPAD)lv_indev_set_group(input,group);
    lv_label_set_text(title,s.mode==Mode::List?"Estoque | Pesquisa":s.mode==Mode::History?"Estoque | Histórico":s.mode==Mode::Pending?"Estoque | Movimento pendente":s.mode==Mode::Form?operation(s.operation):s.mode==Mode::Review?"Estoque | Confirmar movimentação":"Estoque | Saldo");lv_label_set_text(notice,s.message);
    bool listing=s.mode==Mode::List,history=s.mode==Mode::History,form=s.mode==Mode::Form;
    for(auto* object:{query,low,inactive}){if(listing){lv_obj_remove_flag(object,LV_OBJ_FLAG_HIDDEN);lv_group_add_obj(group,object);}else lv_obj_add_flag(object,LV_OBJ_FLAG_HIDDEN);}
    for(auto* object:{quantity,reason,qty_label,reason_label}){if(form)lv_obj_remove_flag(object,LV_OBJ_FLAG_HIDDEN);else lv_obj_add_flag(object,LV_OBJ_FLAG_HIDDEN);}
    if(form){lv_label_set_text(qty_label,s.operation==Action::Count?"Saldo contado (pode ser zero)":"Quantidade positiva (até 3 casas decimais)");for(auto* object:{quantity,reason}){lv_group_add_obj(group,object);if(s.busy)lv_obj_add_state(object,LV_STATE_DISABLED);else lv_obj_remove_state(object,LV_STATE_DISABLED);}}
    if(listing||history){lv_obj_remove_flag(list,LV_OBJ_FLAG_HIDDEN);lv_obj_add_flag(panel,LV_OBJ_FLAG_HIDDEN);}else{lv_obj_add_flag(list,LV_OBJ_FLAG_HIDDEN);lv_obj_remove_flag(panel,LV_OBJ_FLAG_HIDDEN);lv_obj_set_height(panel,form?160:430);lv_label_set_text(summary,s.summary);}
    for(unsigned i=0;i<8;++i){lv_obj_remove_event_cb(rows[i],row_event);if((listing||history)&&i<s.count){lv_obj_remove_flag(rows[i],LV_OBJ_FLAG_HIDDEN);lv_label_set_text(lv_obj_get_child(rows[i],0),s.rows[i].label);if(listing||history){lv_obj_add_event_cb(rows[i],row_event,LV_EVENT_CLICKED,reinterpret_cast<void*>(static_cast<intptr_t>(s.rows[i].id)));lv_group_add_obj(group,rows[i]);}}else lv_obj_add_flag(rows[i],LV_OBJ_FLAG_HIDDEN);}
    const char* names[8]={"","","","","","","","Menu"};if(listing){names[0]="Primeira página";names[1]="Próxima";names[2]="Pesquisar";}if(s.mode==Mode::Detail){if(s.product.active&&has_module_permission(w->permissions,"inventory.adjust")){names[0]="Entrada";names[1]="Saída";names[2]="Contagem / ajuste";}names[3]="Histórico";names[4]="Voltar à pesquisa";}if(form){names[0]="Revisar movimento";names[1]="Voltar";}if(s.mode==Mode::Review){names[0]="Confirmar movimentação";names[1]="Cancelar";}if(s.mode==Mode::Pending){names[0]="Reenviar";names[1]="Resolver tentativa";}if(history){names[0]="Próxima";names[1]="Voltar";}if(s.mode==Mode::Movement){names[0]="Histórico";names[1]="Consultar saldo";}
    for(unsigned i=0;i<8;++i){lv_label_set_text(lv_obj_get_child(buttons[i],0),names[i]);lv_obj_center(lv_obj_get_child(buttons[i],0));if(*names[i]){lv_obj_remove_flag(buttons[i],LV_OBJ_FLAG_HIDDEN);lv_group_add_obj(group,buttons[i]);}else lv_obj_add_flag(buttons[i],LV_OBJ_FLAG_HIDDEN);if((s.busy&&i!=7)||(((listing&&i==1)||(history&&i==0))&&!s.next))lv_obj_add_state(buttons[i],LV_STATE_DISABLED);else lv_obj_remove_state(buttons[i],LV_STATE_DISABLED);}
    static Mode previous=Mode::Blocked;if(previous!=s.mode||s.busy)lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);previous=s.mode;
}
bool decode(cJSON* data,Product& product){memset(&product,0,sizeof(product));product.id=number(data,"id");product.version=number(data,"version");product.active=cJSON_IsTrue(cJSON_GetObjectItemCaseSensitive(data,"active"));product.low=cJSON_IsTrue(cJSON_GetObjectItemCaseSensitive(data,"stock_low"));snprintf(product.name,sizeof(product.name),"%s",text(data,"name"));snprintf(product.sku,sizeof(product.sku),"%s",text(data,"sku"));snprintf(product.unit,sizeof(product.unit),"%s",text(data,"unit"));snprintf(product.stock,sizeof(product.stock),"%s",text(data,"stock"));snprintf(product.minimum,sizeof(product.minimum),"%s",text(data,"stock_min"));snprintf(product.maximum,sizeof(product.maximum),"%s",text(data,"stock_max"));int64_t value;return product.id>0&&product.version>0&&money::parse(product.stock,3,value);}
void show_balance(){auto& p=w->working.product;snprintf(w->working.summary,sizeof(w->working.summary),"%s\nSKU %s | ID %d | %s\n\nSaldo: %s\nMínimo: %s | Máximo: %s\n%s\n\n%s",p.name,p.sku,p.id,p.unit,p.stock,p.minimum,*p.maximum?p.maximum:"não definido",p.low?"Estoque baixo":"Saldo acima do mínimo",p.active?"Escolha Entrada, Saída ou Contagem / ajuste.":"Produto inativo: histórico preservado; novas movimentações bloqueadas.");w->working.mode=Mode::Detail;}
const char* failure(int code,cJSON* data){const char* detail=text(cJSON_GetObjectItemCaseSensitive(data,"error"),"message");return *detail?detail:code<=0?"Sem resposta da API. Confira a conexão.":"Operação recusada. Confira saldo, perfil e campos.";}
} // namespace
void inventory_create(lv_display_t* display,void(*home)()){
    void* memory=heap_caps_calloc(1,sizeof(Workspace),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);if(!memory){ESP_LOGE("inventory","PSRAM indisponível");return;}w=new(memory)Workspace{};mutex=xSemaphoreCreateMutex();auto* storage=static_cast<uint8_t*>(heap_caps_malloc(sizeof(Command),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT));static StaticQueue_t control;queue=xQueueCreateStatic(1,sizeof(Command),storage,&control);home_callback=home;group=lv_group_create();
    root=lv_obj_create(lv_display_get_screen_active(display));lv_obj_set_size(root,1280,720);lv_obj_set_style_pad_all(root,10,0);lv_obj_set_style_text_font(root,&erp_font_pt_20,0);lv_obj_remove_flag(root,LV_OBJ_FLAG_SCROLLABLE);
    title=lv_label_create(root);lv_obj_set_pos(title,8,4);lv_obj_set_style_text_font(title,&erp_font_pt_28,0);notice=lv_label_create(root);lv_obj_set_pos(notice,8,45);lv_obj_set_width(notice,1200);lv_label_set_long_mode(notice,LV_LABEL_LONG_DOT);
    query=lv_textarea_create(root);lv_obj_set_pos(query,8,96);lv_obj_set_size(query,550,48);lv_textarea_set_one_line(query,true);lv_textarea_set_max_length(query,120);lv_textarea_set_placeholder_text(query,"Pesquisar nome ou SKU");low=lv_checkbox_create(root);lv_obj_set_pos(low,590,105);lv_checkbox_set_text(low,"Estoque baixo");inactive=lv_checkbox_create(root);lv_obj_set_pos(inactive,880,105);lv_checkbox_set_text(inactive,"Mostrar inativos");
    list=lv_obj_create(root);lv_obj_set_pos(list,8,160);lv_obj_set_size(list,1220,360);for(unsigned i=0;i<8;++i){rows[i]=lv_button_create(list);lv_obj_set_pos(rows[i],0,i*84);lv_obj_set_size(rows[i],1165,80);auto* label=lv_label_create(rows[i]);lv_obj_set_width(label,1120);lv_label_set_long_mode(label,LV_LABEL_LONG_DOT);lv_obj_center(label);lv_obj_add_event_cb(rows[i],key_event,LV_EVENT_KEY,nullptr);}
    panel=lv_obj_create(root);lv_obj_set_pos(panel,8,88);lv_obj_set_size(panel,1220,430);summary=lv_label_create(panel);lv_obj_set_width(summary,1165);lv_label_set_long_mode(summary,LV_LABEL_LONG_WRAP);
    qty_label=lv_label_create(root);lv_obj_set_pos(qty_label,8,260);quantity=lv_textarea_create(root);lv_obj_set_pos(quantity,8,292);lv_obj_set_size(quantity,580,48);lv_textarea_set_one_line(quantity,true);lv_textarea_set_max_length(quantity,24);
    reason_label=lv_label_create(root);lv_obj_set_pos(reason_label,8,354);lv_label_set_text(reason_label,"Justificativa obrigatória");reason=lv_textarea_create(root);lv_obj_set_pos(reason,8,386);lv_obj_set_size(reason,1220,56);lv_textarea_set_one_line(reason,true);lv_textarea_set_max_length(reason,240);
    for(auto* object:{query,quantity,reason}){lv_obj_add_event_cb(object,keyboard_target,LV_EVENT_FOCUSED,nullptr);lv_obj_add_event_cb(object,keyboard_target,LV_EVENT_CLICKED,nullptr);lv_obj_add_event_cb(object,key_event,LV_EVENT_KEY,nullptr);}
    for(unsigned i=0;i<8;++i){buttons[i]=lv_button_create(root);lv_obj_set_pos(buttons[i],8+(i%4)*306,542+(i/4)*58);lv_obj_set_size(buttons[i],294,50);lv_label_create(buttons[i]);lv_obj_add_event_cb(buttons[i],click,LV_EVENT_CLICKED,reinterpret_cast<void*>(static_cast<uintptr_t>(i)));lv_obj_add_event_cb(buttons[i],key_event,LV_EVENT_KEY,nullptr);}
    keyboard=lv_keyboard_create(root);lv_obj_set_pos(keyboard,8,450);lv_obj_set_size(keyboard,1220,240);for(auto event:{LV_EVENT_READY,LV_EVENT_CANCEL})lv_obj_add_event_cb(keyboard,[](lv_event_t*){lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);},event,nullptr);lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);lv_obj_add_flag(root,LV_OBJ_FLAG_HIDDEN);lv_timer_create(render,100,nullptr);
}
void inventory_hide(){if(!w)return;visible=false;++generation;xQueueReset(queue);lv_obj_add_flag(root,LV_OBJ_FLAG_HIDDEN);xSemaphoreTake(mutex,portMAX_DELAY);memset(&w->state,0,sizeof(w->state));xSemaphoreGive(mutex);for(auto* object:{query,quantity,reason})lv_textarea_set_text(object,"");for(auto* row:rows)lv_label_set_text(lv_obj_get_child(row,0),"");lv_label_set_text(summary,"");lv_label_set_text(notice,"");memset(&w->draw,0,sizeof(w->draw));}
void inventory_open(const char* permissions,bool light){if(!w)return;snprintf(w->permissions,sizeof(w->permissions),"%s",permissions);drawn=0;auto fg=lv_color_hex(light?0x0f172a:0xf8fafc),bg=lv_color_hex(light?0xe2e8f0:0x334155);lv_obj_set_style_bg_color(root,lv_color_hex(light?0xf1f5f9:0x111827),0);lv_obj_set_style_text_color(root,fg,0);for(auto* object:{list,panel})lv_obj_set_style_bg_color(object,lv_color_hex(light?0xffffff:0x1e293b),0);for(auto* object:{query,quantity,reason}){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}for(auto* object:rows){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}for(auto* object:buttons){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}lv_obj_set_style_bg_color(keyboard,bg,LV_PART_ITEMS);lv_obj_set_style_text_color(keyboard,fg,LV_PART_ITEMS);visible=true;lv_obj_remove_flag(root,LV_OBJ_FLAG_HIDDEN);enqueue(Action::Init);render(nullptr);}
bool inventory_handle_next(const char* permissions,bool online,ProductTransport transport,SaleJournal journal){if(!w||xQueueReceive(queue,&w->command,0)!=pdTRUE)return false;const Command& cmd=w->command;if(cmd.generation!=generation)return true;xSemaphoreTake(mutex,portMAX_DELAY);w->working=w->state;xSemaphoreGive(mutex);
    auto done=[&](const char* message){publish(cmd,message);return true;};if(!online)return done("Sem rede. Consulte e movimente estoque apenas com a API disponível.");
    auto call=[&](const char* method,const char* path,const char* body){memset(w->response,0,sizeof(w->response));return transport(method,path,body,w->response,sizeof(w->response));};
    if(cmd.action==Action::Init){int code=call("GET","/api/v1/auth/me",nullptr);auto* data=cJSON_Parse(w->response);w->working.user=number(data,"id");cJSON_Delete(data);if(code!=200||!w->working.user)return done("Não foi possível confirmar a sessão.");int loaded=journal("load",w->working.user,w->pending,sizeof(w->pending));w->working.pending=loaded!=0;if(loaded!=0){w->working.mode=loaded>0?Mode::Pending:Mode::Blocked;snprintf(w->working.summary,sizeof(w->working.summary),"Tentativa protegida no microSD. Reenviar repete o mesmo pedido. Resolver confirma o resultado ou encerra essa tentativa antes de permitir novo movimento.");return done(loaded>0?"Movimento pendente recuperado. Resolva antes de continuar.":"Pendência protegida. Use o dispositivo, operador e API originais; preserve o microSD.");}}
    if(w->working.pending&&cmd.action!=Action::Retry&&cmd.action!=Action::Resolve)return done("Resolva a movimentação pendente antes de continuar.");
    bool mutation=cmd.action==Action::Entry||cmd.action==Action::Exit||cmd.action==Action::Count||cmd.action==Action::Review||cmd.action==Action::Send||cmd.action==Action::Retry||cmd.action==Action::Resolve;
    if(!has_module_permission(permissions,mutation?"inventory.adjust":"inventory.read"))return done("Seu perfil não permite esta operação.");
    if(cmd.action==Action::Entry||cmd.action==Action::Exit||cmd.action==Action::Count){w->working.operation=cmd.action;w->working.mode=Mode::Form;snprintf(w->working.summary,sizeof(w->working.summary),"%s | SKU %s\nSaldo atual: %s %s\n%s",w->working.product.name,w->working.product.sku,w->working.product.stock,w->working.product.unit,cmd.action==Action::Count?"Informe o saldo total contado; ele substituirá o saldo atual.":"Informe a quantidade a acrescentar ou retirar.");return done("Informe quantidade e justificativa; revise antes de confirmar.");}
    char path[180];const char* method="GET";const char* body=nullptr;
    if(cmd.action==Action::Review){int64_t qty=0,before=0;constexpr int64_t maximum=999999999999999LL;if(!money::parse(cmd.quantity,3,qty)||qty>maximum||(w->working.operation!=Action::Count&&qty==0)||strlen(cmd.reason)<3)return done("Confira quantidade e justificativa (mínimo de 3 caracteres).");snprintf(path,sizeof(path),"/api/v1/inventory/%d",w->working.product.id);int code=call("GET",path,nullptr);auto* data=cJSON_Parse(w->response);Product fresh{};bool valid=code==200&&decode(data,fresh);cJSON_Delete(data);if(!valid)return done("Não foi possível confirmar o saldo atual.");if(!fresh.active||fresh.version!=w->working.product.version){w->working.product=fresh;show_balance();return done("Saldo/cadastro alterado. Confira o saldo e informe o movimento novamente.");}if(!money::parse(fresh.stock,3,before))return done("Saldo inválido recebido da API.");int64_t after=w->working.operation==Action::Count?qty:before+(w->working.operation==Action::Entry?qty:-qty);if(after<0||after>maximum||after==before)return done("Confira quantidade: saldo não pode ser negativo ou permanecer igual.");auto* request=cJSON_CreateObject();cJSON_AddNumberToObject(request,"product_id",fresh.id);cJSON_AddNumberToObject(request,"product_version",fresh.version);cJSON_AddStringToObject(request,"kind",kind(w->working.operation));char amount[48],result[48];money::format(amount,sizeof(amount),qty,3);money::format(result,sizeof(result),after,3);cJSON_AddStringToObject(request,w->working.operation==Action::Count?"target_quantity":"quantity",amount);cJSON_AddStringToObject(request,"reason",cmd.reason);char* raw=cJSON_PrintUnformatted(request);cJSON_Delete(request);if(!raw||strlen(raw)>=sizeof(w->body)){cJSON_free(raw);return done("Movimento excede limite de armazenamento.");}snprintf(w->body,sizeof(w->body),"%s",raw);cJSON_free(raw);w->working.mode=Mode::Review;snprintf(w->working.summary,sizeof(w->working.summary),"%s\n%s | SKU %s\n\nSaldo anterior: %s\n%s: %s\nSaldo previsto: %s\n\nJustificativa: %s\n\nConfira os valores antes de confirmar.",operation(w->working.operation),fresh.name,fresh.sku,fresh.stock,w->working.operation==Action::Count?"Saldo contado":"Quantidade",amount,result,cmd.reason);return done("A API confirmará saldo, versão e permissão ao gravar.");}
    if(cmd.action==Action::Send){if(w->working.mode!=Mode::Review||!w->body[0])return done("Revise o movimento antes de confirmar.");auto* request=cJSON_Parse(w->body);uint8_t random[16];esp_fill_random(random,sizeof(random));char key[33];for(unsigned i=0;i<16;++i)snprintf(key+2*i,3,"%02x",random[i]);cJSON_AddStringToObject(request,"idempotency_key",key);char* raw=cJSON_PrintUnformatted(request);cJSON_Delete(request);if(!raw||strlen(raw)>=sizeof(w->pending)){cJSON_free(raw);return done("Não foi possível registrar o pedido.");}snprintf(w->pending,sizeof(w->pending),"%s",raw);cJSON_free(raw);if(journal("save",w->working.user,w->pending,sizeof(w->pending))!=1)return done("Falha ao registrar tentativa no microSD. Movimento não enviado.");w->working.pending=true;w->working.mode=Mode::Pending;}
    if(cmd.action==Action::Send||cmd.action==Action::Retry){snprintf(path,sizeof(path),"/api/v1/inventory/adjustments");method="POST";body=w->pending;}
    else if(cmd.action==Action::Resolve){auto* request=cJSON_Parse(w->pending);const char* key=text(request,"idempotency_key");if(strlen(key)<16||strlen(key)>64){cJSON_Delete(request);return done("Registro pendente inválido. Preserve o microSD para recuperação.");}snprintf(path,sizeof(path),"/api/v1/inventory/requests/%s/resolve",key);cJSON_Delete(request);method="POST";}
    else if(cmd.action==Action::Get)snprintf(path,sizeof(path),"/api/v1/inventory/%d",cmd.id?cmd.id:w->working.product.id);
    else if(cmd.action==Action::Movement)snprintf(path,sizeof(path),"/api/v1/inventory/movements/%d",cmd.id);
    else if(cmd.action==Action::History)snprintf(path,sizeof(path),"/api/v1/inventory/%d/movements?limit=8&after_id=%u",w->working.product.id,cmd.after);
    else{std::string term;for(const unsigned char* p=reinterpret_cast<const unsigned char*>(cmd.query);*p;++p){char encoded[4];snprintf(encoded,sizeof(encoded),"%%%02X",*p);term+=encoded;}std::string url="/api/v1/inventory?q="+term+"&limit=8&after_id="+std::to_string(cmd.after)+"&low_only="+(cmd.low?"true":"false")+"&include_inactive="+(cmd.inactive?"true":"false");if(cmd.after&&w->working.revision)url+="&revision="+std::to_string(w->working.revision);int code=call("GET",url.c_str(),nullptr);auto* data=cJSON_Parse(w->response);if(code!=200){std::string message=failure(code,data);cJSON_Delete(data);return done(message.c_str());}w->working.mode=Mode::List;w->working.count=0;w->working.next=number(data,"next_id");w->working.revision=number(data,"revision");cJSON* item;auto* items=cJSON_GetObjectItemCaseSensitive(data,"items");cJSON_ArrayForEach(item,items){if(w->working.count==8)break;auto& row=w->working.rows[w->working.count++];row.id=number(item,"id");snprintf(row.label,sizeof(row.label),"%s | SKU %s | ID %d\nSaldo %s %s | Mínimo %s%s%s",text(item,"name"),text(item,"sku"),row.id,text(item,"stock"),text(item,"unit"),text(item,"stock_min"),cJSON_IsTrue(cJSON_GetObjectItemCaseSensitive(item,"stock_low"))?" | BAIXO":"",cJSON_IsTrue(cJSON_GetObjectItemCaseSensitive(item,"active"))?"":" | Inativo");}cJSON_Delete(data);return done("Toque no produto para consultar saldo ou movimentar.");}
    int code=call(method,path,body);auto* data=cJSON_Parse(w->response);std::string message;
    if(code<200||code>=300){message=failure(code,data);if(w->working.pending){w->working.mode=Mode::Pending;snprintf(w->working.summary,sizeof(w->working.summary),"Resultado não confirmado. Reenviar usa a mesma chave; Resolver confirma ou encerra a tentativa na API. Não remova a pendência para repetir o movimento.");}}
    else if(cmd.action==Action::Get){if(decode(data,w->working.product)){show_balance();message="Saldo consultado na API.";}else message="Resposta de saldo inválida.";}
    else if(cmd.action==Action::Movement){if(number(data,"id")<=0)message="Resposta de movimento inválida.";else{w->working.mode=Mode::Movement;snprintf(w->working.summary,sizeof(w->working.summary),"%s | Movimento %d\nProduto ID %d | Venda ID %d\nOperador %d | %s\n\nSaldo anterior: %s\nVariação: %s\nSaldo após: %s\n\nJustificativa: %s",movement_kind(text(data,"kind")),number(data,"id"),number(data,"product_id"),number(data,"sale_id"),number(data,"operator_id"),text(data,"created_at"),text(data,"before"),text(data,"quantity"),text(data,"after"),text(data,"reason"));message="Movimentação auditada. Saldos registrados no momento da operação.";}}
    else if(cmd.action==Action::History){w->working.mode=Mode::History;w->working.count=0;w->working.next=number(data,"next_id");cJSON* item;auto* items=cJSON_GetObjectItemCaseSensitive(data,"items");cJSON_ArrayForEach(item,items){if(w->working.count==8)break;auto& row=w->working.rows[w->working.count++];row.id=number(item,"id");snprintf(row.label,sizeof(row.label),"%s | %s | Operador %d\n%s -> %s | Variação %s | %s",text(item,"created_at"),movement_kind(text(item,"kind")),number(item,"operator_id"),text(item,"before"),text(item,"after"),text(item,"quantity"),text(item,"reason"));}message="Histórico preservado: entradas, saídas, ajustes, vendas e cancelamentos.";}
    else if(cmd.action==Action::Resolve&&!strcmp(text(data,"state"),"abandoned")){if(journal("clear",w->working.user,w->pending,sizeof(w->pending))==1){w->working.pending=false;w->pending[0]=0;w->working.mode=Mode::List;w->working.count=0;w->working.next=0;message="Tentativa encerrada. Pesquise novamente o saldo antes de movimentar.";}else message="Tentativa encerrada; resolva novamente para limpar o registro no cartão.";}
    else{auto* result=cmd.action==Action::Resolve?cJSON_GetObjectItemCaseSensitive(data,"movement"):data;if(number(result,"id")<=0)message="Resposta inválida. Preserve a tentativa pendente.";else{snprintf(w->working.summary,sizeof(w->working.summary),"Movimentação concluída\nID %d | Produto ID %d\n%s\n\nSaldo anterior: %s\nVariação: %s\nSaldo após o movimento: %s\n\nJustificativa: %s\nOperador %d | %s\n\nPesquise novamente para consultar o saldo mais recente.",number(result,"id"),number(result,"product_id"),movement_kind(text(result,"kind")),text(result,"before"),text(result,"quantity"),text(result,"after"),text(result,"reason"),number(result,"operator_id"),text(result,"created_at"));w->working.product.id=number(result,"product_id");w->working.product.active=false;w->working.mode=Mode::Detail;if(journal("clear",w->working.user,w->pending,sizeof(w->pending))==1){w->working.pending=false;w->pending[0]=0;message="Movimentação concluída. Saldo e histórico gravados na API.";}else{w->working.mode=Mode::Pending;message="Movimento confirmado; resolva novamente para limpar o registro no cartão.";}}}
    cJSON_Delete(data);return done(message.c_str());
}
} // namespace tab5
