#include "reports.hpp"
#include "module_policy.hpp"
#include "finance_input.hpp"
#include "erp_fonts.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "cJSON.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include <atomic>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <ctime>
#include <new>
#include <string>
namespace tab5 { namespace {
constexpr const char* kinds[]={"sales","sellers","products","payments","cancellations","stock","low-stock","movements","cash","cash-sessions","receivables","payables"};
constexpr const char* captions[]={"Vendas no período","Vendas por vendedor","Produtos mais vendidos","Vendas por pagamento","Cancelamentos","Estoque atual","Estoque baixo","Histórico de estoque","Movimentações de caixa","Resumo dos caixas","Contas a receber","Contas a pagar"};
struct Row {char label[1700];};
struct State {unsigned serial,count,next,total,offset;bool busy,has_next;Row rows[8];char message[350],summary[4096],revision[65];};
struct Command {unsigned generation,kind,offset;bool open,inactive;char from[24],to[24],operator_id[24],product_id[24];};
struct Workspace {State state,draw,working;Command command,last;char response[16385],permissions[2048];};
Workspace* w;SemaphoreHandle_t mutex;QueueHandle_t queue;std::atomic<unsigned> generation{0};std::atomic<bool> visible{false};unsigned drawn;
lv_obj_t *root,*title,*notice,*selector,*from,*to,*operator_id,*product_id,*open_only,*inactive,*summary_panel,*summary,*list,*rows[8],*buttons[4],*keyboard;
lv_group_t* group;void(*home_callback)();
const char* text(cJSON* data,const char* key){auto* v=cJSON_GetObjectItemCaseSensitive(data,key);return cJSON_IsString(v)?v->valuestring:"";}
int number(cJSON* data,const char* key){auto* v=cJSON_GetObjectItemCaseSensitive(data,key);return cJSON_IsNumber(v)?v->valueint:0;}
void publish(const Command& cmd,const char* msg){xSemaphoreTake(mutex,portMAX_DELAY);if(cmd.generation==generation){w->working.busy=false;snprintf(w->working.message,sizeof(w->working.message),"%s",msg);w->working.serial=w->state.serial+1;w->state=w->working;}xSemaphoreGive(mutex);}
void enqueue(unsigned offset=0){if(!visible)return;Command cmd{};cmd.generation=generation;cmd.kind=lv_dropdown_get_selected(selector);cmd.offset=offset;cmd.open=lv_obj_has_state(open_only,LV_STATE_CHECKED);cmd.inactive=lv_obj_has_state(inactive,LV_STATE_CHECKED);snprintf(cmd.from,sizeof(cmd.from),"%s",lv_textarea_get_text(from));snprintf(cmd.to,sizeof(cmd.to),"%s",lv_textarea_get_text(to));snprintf(cmd.operator_id,sizeof(cmd.operator_id),"%s",lv_textarea_get_text(operator_id));snprintf(cmd.product_id,sizeof(cmd.product_id),"%s",lv_textarea_get_text(product_id));xSemaphoreTake(mutex,portMAX_DELAY);if(!w->state.busy&&xQueueSend(queue,&cmd,0)==pdTRUE){w->state.busy=true;++w->state.serial;snprintf(w->state.message,sizeof(w->state.message),"Consultando relatório...");}xSemaphoreGive(mutex);}
void keyboard_target(lv_event_t* e){lv_keyboard_set_textarea(keyboard,lv_event_get_target_obj(e));if(lv_event_get_code(e)==LV_EVENT_CLICKED)lv_obj_remove_flag(keyboard,LV_OBJ_FLAG_HIDDEN);}
void key_event(lv_event_t* e){auto key=lv_event_get_key(e);if(key==LV_KEY_ESC){if(!lv_obj_has_flag(keyboard,LV_OBJ_FLAG_HIDDEN))lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);else{reports_hide();home_callback();}}else if(key==LV_KEY_UP)lv_group_focus_prev(group);else if(key==LV_KEY_DOWN)lv_group_focus_next(group);}
void click(lv_event_t* e){unsigned index=reinterpret_cast<uintptr_t>(lv_event_get_user_data(e));if(index==3){reports_hide();home_callback();return;}if(!w->draw.busy)enqueue(index==1?w->draw.next:0);}
void selector_changed(lv_event_t*){unsigned kind=lv_dropdown_get_selected(selector);if(kind>=12)return;bool stock=kind==5||kind==6;if(stock){lv_textarea_set_text(from,"");lv_textarea_set_text(to,"");}bool accounts=kind>=10;bool products=stock||kind==2||kind==7;for(auto* input:{from,to}){if(stock)lv_obj_add_state(input,LV_STATE_DISABLED);else lv_obj_remove_state(input,LV_STATE_DISABLED);}if(stock||accounts){lv_textarea_set_text(operator_id,"");lv_obj_add_state(operator_id,LV_STATE_DISABLED);}else lv_obj_remove_state(operator_id,LV_STATE_DISABLED);if(!products){lv_textarea_set_text(product_id,"");lv_obj_add_state(product_id,LV_STATE_DISABLED);}else lv_obj_remove_state(product_id,LV_STATE_DISABLED);if(accounts)lv_obj_remove_state(open_only,LV_STATE_DISABLED);else{lv_obj_remove_state(open_only,LV_STATE_CHECKED);lv_obj_add_state(open_only,LV_STATE_DISABLED);}if(stock)lv_obj_remove_state(inactive,LV_STATE_DISABLED);else{lv_obj_remove_state(inactive,LV_STATE_CHECKED);lv_obj_add_state(inactive,LV_STATE_DISABLED);}}
void render(lv_timer_t*){if(!visible)return;xSemaphoreTake(mutex,portMAX_DELAY);w->draw=w->state;xSemaphoreGive(mutex);auto& s=w->draw;if(s.serial==drawn)return;drawn=s.serial;lv_label_set_text(notice,s.message);lv_label_set_text(summary,s.summary);lv_group_remove_all_objs(group);lv_group_set_default(group);for(auto* indev=lv_indev_get_next(nullptr);indev;indev=lv_indev_get_next(indev))if(lv_indev_get_type(indev)==LV_INDEV_TYPE_KEYPAD)lv_indev_set_group(indev,group);for(auto* object:{selector,from,to,operator_id,product_id,open_only,inactive})lv_group_add_obj(group,object);int row_y=0;for(unsigned i=0;i<8;++i){if(i<s.count){lv_obj_remove_flag(rows[i],LV_OBJ_FLAG_HIDDEN);lv_label_set_text(lv_obj_get_child(rows[i],0),s.rows[i].label);lv_obj_set_pos(rows[i],0,row_y);lv_obj_set_height(rows[i],LV_SIZE_CONTENT);lv_obj_update_layout(rows[i]);row_y+=lv_obj_get_height(rows[i])+8;lv_group_add_obj(group,rows[i]);}else lv_obj_add_flag(rows[i],LV_OBJ_FLAG_HIDDEN);}for(unsigned i=0;i<4;++i){lv_group_add_obj(group,buttons[i]);if((s.busy&&i!=3)||(i==1&&!s.has_next))lv_obj_add_state(buttons[i],LV_STATE_DISABLED);else lv_obj_remove_state(buttons[i],LV_STATE_DISABLED);}if(s.busy)lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);}
const char* label(const char* key){if(!strcmp(key,"sales"))return "Vendas";if(!strcmp(key,"gross"))return "Bruto R$";if(!strcmp(key,"discount"))return "Descontos R$";if(!strcmp(key,"total"))return "Total R$";if(!strcmp(key,"products"))return "Produtos";if(!strcmp(key,"quantity"))return "Quantidade";if(!strcmp(key,"movements"))return "Movimentos";if(!strcmp(key,"cancellations"))return "Cancelamentos";if(!strcmp(key,"inflows"))return "Entradas R$";if(!strcmp(key,"outflows"))return "Saídas R$";if(!strcmp(key,"cash_net"))return "Variação em dinheiro R$";if(!strcmp(key,"sessions"))return "Caixas";if(!strcmp(key,"closed"))return "Fechados";if(!strcmp(key,"opening"))return "Fundos iniciais R$";if(!strcmp(key,"closed_expected"))return "Esperado dos fechados R$";if(!strcmp(key,"closed_counted"))return "Contado dos fechados R$";if(!strcmp(key,"closed_difference"))return "Diferença dos fechados R$";if(!strcmp(key,"accounts"))return "Contas";if(!strcmp(key,"original"))return "Original R$";if(!strcmp(key,"paid"))return "Baixado R$";if(!strcmp(key,"remaining"))return "Saldo R$";return nullptr;}
const char* translate(const char* value){if(!strcmp(value,"cash"))return "Dinheiro";if(!strcmp(value,"pix"))return "Pix";if(!strcmp(value,"debit"))return "Débito";if(!strcmp(value,"credit"))return "Crédito";if(!strcmp(value,"transfer"))return "Transferência";if(!strcmp(value,"other"))return "Outros";if(!strcmp(value,"sale"))return "Venda";if(!strcmp(value,"sale_reversal"))return "Estorno gerencial";if(!strcmp(value,"deposit"))return "Suprimento";if(!strcmp(value,"withdraw"))return "Sangria";if(!strcmp(value,"settlement"))return "Baixa";if(!strcmp(value,"open"))return "Aberto";if(!strcmp(value,"closed"))return "Fechado";if(!strcmp(value,"inventory_entry"))return "Entrada";if(!strcmp(value,"inventory_exit"))return "Saída";if(!strcmp(value,"inventory_adjustment"))return "Contagem";if(!strcmp(value,"opening"))return "Saldo inicial";if(!strcmp(value,"cancellation"))return "Cancelamento";return value;}
} // namespace
void reports_create(lv_display_t* display,void(*home)()){
    void* memory=heap_caps_calloc(1,sizeof(Workspace),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);if(!memory){ESP_LOGE("reports","PSRAM indisponível");return;}w=new(memory)Workspace{};mutex=xSemaphoreCreateMutex();auto* storage=static_cast<uint8_t*>(heap_caps_malloc(sizeof(Command),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT));static StaticQueue_t control;queue=xQueueCreateStatic(1,sizeof(Command),storage,&control);home_callback=home;group=lv_group_create();
    root=lv_obj_create(lv_display_get_screen_active(display));lv_obj_set_size(root,1280,720);lv_obj_set_style_pad_all(root,10,0);lv_obj_set_style_text_font(root,&erp_font_pt_20,0);lv_obj_remove_flag(root,LV_OBJ_FLAG_SCROLLABLE);title=lv_label_create(root);lv_obj_set_pos(title,8,4);lv_obj_set_style_text_font(title,&erp_font_pt_28,0);lv_label_set_text(title,"Relatórios | Consultas gerenciais");notice=lv_label_create(root);lv_obj_set_pos(notice,8,45);lv_obj_set_width(notice,1200);lv_label_set_long_mode(notice,LV_LABEL_LONG_DOT);
    selector=lv_dropdown_create(root);lv_obj_set_pos(selector,8,96);lv_obj_set_size(selector,430,48);lv_dropdown_set_options(selector,"Vendas no período\nVendas por vendedor\nProdutos mais vendidos\nVendas por pagamento\nCancelamentos\nEstoque atual\nEstoque baixo\nHistórico de estoque\nMovimentações de caixa\nResumo dos caixas\nContas a receber\nContas a pagar");lv_obj_add_event_cb(selector,selector_changed,LV_EVENT_VALUE_CHANGED,nullptr);lv_obj_add_event_cb(selector,key_event,LV_EVENT_KEY,nullptr);
    from=lv_textarea_create(root);to=lv_textarea_create(root);operator_id=lv_textarea_create(root);product_id=lv_textarea_create(root);unsigned i=0;for(auto* object:{from,to,operator_id,product_id}){lv_obj_set_pos(object,i<2?460+(i%2)*385:8+(i%2)*310,i<2?96:166);lv_obj_set_size(object,i<2?365:290,48);lv_textarea_set_one_line(object,true);lv_textarea_set_max_length(object,10);lv_textarea_set_placeholder_text(object,i==0?"Desde AAAA-MM-DD":i==1?"Até AAAA-MM-DD":i==2?"ID operador (opcional)":"ID produto (opcional)");lv_obj_add_event_cb(object,keyboard_target,LV_EVENT_FOCUSED,nullptr);lv_obj_add_event_cb(object,keyboard_target,LV_EVENT_CLICKED,nullptr);lv_obj_add_event_cb(object,key_event,LV_EVENT_KEY,nullptr);++i;}
    open_only=lv_checkbox_create(root);lv_obj_set_pos(open_only,640,177);lv_checkbox_set_text(open_only,"Contas em aberto");inactive=lv_checkbox_create(root);lv_obj_set_pos(inactive,950,177);lv_checkbox_set_text(inactive,"Mostrar inativos");
    summary_panel=lv_obj_create(root);lv_obj_set_pos(summary_panel,8,232);lv_obj_set_size(summary_panel,1220,130);summary=lv_label_create(summary_panel);lv_obj_set_width(summary,1165);lv_label_set_long_mode(summary,LV_LABEL_LONG_WRAP);
    list=lv_obj_create(root);lv_obj_set_pos(list,8,374);lv_obj_set_size(list,1220,226);for(unsigned j=0;j<8;++j){rows[j]=lv_button_create(list);lv_obj_set_pos(rows[j],0,j*250);lv_obj_set_size(rows[j],1165,244);auto* value=lv_label_create(rows[j]);lv_obj_set_width(value,1120);lv_label_set_long_mode(value,LV_LABEL_LONG_WRAP);lv_obj_add_event_cb(rows[j],key_event,LV_EVENT_KEY,nullptr);}
    const char* names[]={"Primeira página","Próxima","Consultar / atualizar","Menu"};for(unsigned j=0;j<4;++j){buttons[j]=lv_button_create(root);lv_obj_set_pos(buttons[j],8+j*306,622);lv_obj_set_size(buttons[j],294,50);auto* value=lv_label_create(buttons[j]);lv_label_set_text(value,names[j]);lv_obj_center(value);lv_obj_add_event_cb(buttons[j],click,LV_EVENT_CLICKED,reinterpret_cast<void*>(static_cast<uintptr_t>(j)));lv_obj_add_event_cb(buttons[j],key_event,LV_EVENT_KEY,nullptr);}
    keyboard=lv_keyboard_create(root);lv_obj_set_pos(keyboard,8,450);lv_obj_set_size(keyboard,1220,240);for(auto event:{LV_EVENT_READY,LV_EVENT_CANCEL})lv_obj_add_event_cb(keyboard,[](lv_event_t*){lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);},event,nullptr);lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);lv_obj_add_flag(root,LV_OBJ_FLAG_HIDDEN);lv_timer_create(render,100,nullptr);
}
void reports_hide(){if(!w)return;visible=false;++generation;xQueueReset(queue);lv_obj_add_flag(root,LV_OBJ_FLAG_HIDDEN);xSemaphoreTake(mutex,portMAX_DELAY);memset(&w->state,0,sizeof(w->state));xSemaphoreGive(mutex);memset(&w->draw,0,sizeof(w->draw));for(auto* input:{from,to,operator_id,product_id})lv_textarea_set_text(input,"");lv_label_set_text(summary,"");lv_label_set_text(notice,"");for(auto* row:rows)lv_label_set_text(lv_obj_get_child(row,0),"");}
void reports_open(const char* permissions,bool light){if(!w)return;snprintf(w->permissions,sizeof(w->permissions),"%s",permissions);drawn=0;auto fg=lv_color_hex(light?0x0f172a:0xf8fafc),bg=lv_color_hex(light?0xe2e8f0:0x334155);lv_obj_set_style_bg_color(root,lv_color_hex(light?0xf1f5f9:0x111827),0);lv_obj_set_style_text_color(root,fg,0);for(auto* object:{list,summary_panel})lv_obj_set_style_bg_color(object,lv_color_hex(light?0xffffff:0x1e293b),0);for(auto* object:{selector,from,to,operator_id,product_id}){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}auto* drop=lv_dropdown_get_list(selector);if(drop){lv_obj_set_style_bg_color(drop,bg,0);lv_obj_set_style_text_color(drop,fg,0);lv_obj_set_style_text_font(drop,&erp_font_pt_20,0);}for(auto* object:rows){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}for(auto* object:buttons){lv_obj_set_style_bg_color(object,bg,0);lv_obj_set_style_text_color(object,fg,0);}lv_obj_set_style_bg_color(keyboard,bg,LV_PART_ITEMS);lv_obj_set_style_text_color(keyboard,fg,LV_PART_ITEMS);lv_dropdown_set_selected(selector,has_module_permission(permissions,"reports.financial")?0:5);selector_changed(nullptr);visible=true;lv_obj_remove_flag(root,LV_OBJ_FLAG_HIDDEN);enqueue();render(nullptr);}

bool reports_handle_next(const char* permissions,bool online,ProductTransport transport){if(!w||xQueueReceive(queue,&w->command,0)!=pdTRUE)return false;const auto& cmd=w->command;if(cmd.generation!=generation)return true;xSemaphoreTake(mutex,portMAX_DELAY);w->working=w->state;xSemaphoreGive(mutex);auto& s=w->working;auto done=[&](const char* message){publish(cmd,message);return true;};if(!has_module_permission(permissions,"reports.read"))return done("Seu perfil não permite consultar relatórios.");if(cmd.kind>=12)return done("Selecione um relatório válido.");if(cmd.kind!=5&&cmd.kind!=6&&cmd.kind!=7&&!has_module_permission(permissions,"reports.financial"))return done("Seu perfil não permite relatórios financeiros.");if(!online)return done("Sem conexão. Relatórios precisam da API disponível.");if((cmd.from[0]&&!valid_financial_date(cmd.from))||(cmd.to[0]&&!valid_financial_date(cmd.to)))return done("Confira as datas: AAAA-MM-DD. Campos vazios consultam o dia atual.");
    auto identity=[](const char* value){if(!*value)return true;for(const char* p=value;*p;++p)if(*p<'0'||*p>'9')return false;return strtoull(value,nullptr,10)>0&&strtoull(value,nullptr,10)<=2147483647ULL;};if(!identity(cmd.operator_id)||!identity(cmd.product_id))return done("Informe IDs numéricos positivos, ou deixe os campos vazios.");
    if(cmd.offset&&(cmd.kind!=w->last.kind||strcmp(cmd.from,w->last.from)||strcmp(cmd.to,w->last.to)||strcmp(cmd.operator_id,w->last.operator_id)||strcmp(cmd.product_id,w->last.product_id)||cmd.open!=w->last.open||cmd.inactive!=w->last.inactive))return done("Filtros alterados. Consulte a primeira página.");
    std::string url=std::string("/api/v1/reports/")+kinds[cmd.kind]+"?limit=8&offset="+std::to_string(cmd.offset)+"&only_open="+(cmd.open?"true":"false")+"&include_inactive="+(cmd.inactive?"true":"false");if(cmd.from[0])url+="&from_date="+std::string(cmd.from);if(cmd.to[0])url+="&to_date="+std::string(cmd.to);if(cmd.operator_id[0])url+="&operator_id="+std::string(cmd.operator_id);if(cmd.product_id[0])url+="&product_id="+std::string(cmd.product_id);if(cmd.offset)url+="&revision="+std::string(s.revision);
    memset(w->response,0,sizeof(w->response));int code=transport("GET",url.c_str(),nullptr,w->response,sizeof(w->response));auto* data=cJSON_Parse(w->response);if(code!=200){std::string message=text(cJSON_GetObjectItemCaseSensitive(data,"error"),"message");if(message.empty())message=code<=0?"Sem resposta da API. Confira rede e servidor.":"Não foi possível consultar o relatório.";s.has_next=false;s.count=0;s.summary[0]=0;cJSON_Delete(data);return done(message.c_str());}if(strcmp(text(data,"kind"),kinds[cmd.kind])||strlen(text(data,"revision"))!=64||!cJSON_IsArray(cJSON_GetObjectItemCaseSensitive(data,"rows"))){cJSON_Delete(data);return done("Resposta de relatório inválida.");}
    s.count=0;s.total=number(data,"rows_total");s.offset=cmd.offset;auto* next=cJSON_GetObjectItemCaseSensitive(data,"next_offset");s.has_next=cJSON_IsNumber(next);s.next=s.has_next?next->valueint:0;snprintf(s.revision,sizeof(s.revision),"%s",text(data,"revision"));snprintf(s.summary,sizeof(s.summary),"%s | %s a %s | Horário de Cuiabá\nRegistros: %u | Página %u\n",captions[cmd.kind],text(data,"from_date"),text(data,"to_date"),s.total,cmd.offset/8+1);auto* totals=cJSON_GetObjectItemCaseSensitive(data,"summary");cJSON* value; cJSON_ArrayForEach(value,totals){const char* name=label(value->string);if(!name)continue;char numeric[48];snprintf(numeric,sizeof(numeric),"%.0f",value->valuedouble);size_t used=strlen(s.summary);snprintf(s.summary+used,sizeof(s.summary)-used,"%s: %s | ",name,cJSON_IsString(value)?value->valuestring:numeric);}auto* columns=cJSON_GetObjectItemCaseSensitive(data,"columns");auto* values=cJSON_GetObjectItemCaseSensitive(data,"rows");cJSON* row;cJSON_ArrayForEach(row,values){if(s.count==8)break;auto& output=s.rows[s.count++];output.label[0]=0;unsigned index=0;cJSON* cell;cJSON_ArrayForEach(cell,row){auto* col=cJSON_GetArrayItem(columns,index++);if(!cJSON_IsString(col)||!cJSON_IsString(cell))continue;size_t used=strlen(output.label);snprintf(output.label+used,sizeof(output.label)-used,"%s: %s\n",col->valuestring,(!strcmp(col->valuestring,"Forma")||!strcmp(col->valuestring,"Tipo")||!strcmp(col->valuestring,"Situação"))?translate(cell->valuestring):cell->valuestring);}}w->last=cmd;cJSON_Delete(data);return done(cmd.kind==5||cmd.kind==6?"Saldo ATUAL por unidade. As datas não reconstituem estoque histórico.":cmd.kind>=10?"Período por vencimento. Baixas e saldo refletem a situação atual.":"Totais do período completo; a lista está paginada. Datas dos registros no horário de Cuiabá.");
}
} // namespace tab5
