#include "sales.hpp"
#include "module_policy.hpp"
#include "erp_fonts.h"
#include "money.hpp"
#include "esp_heap_caps.h"
#include "esp_random.h"
#include "esp_log.h"
#include "cJSON.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include <atomic>
#include <cstring>
#include <cstdio>
#include <string>
#include <new>

namespace tab5 { namespace {
constexpr unsigned field_count=11,max_items=8;
const char* captions[]={"Produto ID","Quantidade","Desc. item R$","Desc. item %","Cliente ID (0=sem)","Desc. venda R$","Desc. venda %","Pagamento 1 R$","Pagamento 2 R$","Pesquisar produto","Motivo cancelamento"};
const char* methods[]={"cash","pix","debit","credit","transfer","other"};
enum class Mode {Cart,Search,CustomerSearch,Review,Pending,Receipt,History,Cancel,Blocked};
enum class Action {Init,Add,Remove,Search,CustomerSearch,Select,Refresh,Quote,Finish,Retry,Resolve,History,Detail,Cancel,New};
struct Item {int id,version;char name[481];int64_t price,quantity,amount,percent;};
struct Row {int id;char label[650];};
struct State {unsigned serial,count,next;int user,sale;bool busy,pending,canceled;Mode mode;Item items[max_items];unsigned size;Row rows[8];char message[350],summary[16385];};
struct Command {Action action;unsigned generation,after;int id;unsigned payment[2];char fields[field_count][961];};
struct Workspace {State state,draw,working;Command command;char permissions[2048],response[16385],payload[4097],pending[4097];};
Workspace* w;QueueHandle_t queue;SemaphoreHandle_t mutex;std::atomic<unsigned> generation{0};std::atomic<bool> visible{false};
lv_obj_t *root,*title,*notice,*preview,*list,*receipt_panel,*summary,*fields[field_count],*labels[field_count],*rows[8],*buttons[8],*payments[2],*keyboard;void(*home_callback)();unsigned drawn=0;
const char* value(cJSON* o,const char* key){auto* v=cJSON_GetObjectItemCaseSensitive(o,key);return cJSON_IsString(v)?v->valuestring:"";}
int integer(cJSON* o,const char* key){auto* v=cJSON_GetObjectItemCaseSensitive(o,key);return cJSON_IsNumber(v)?v->valueint:0;}
bool permitted(const char* p,const char* code){return has_module_permission(p,code);}
void publish(const Command& cmd,const char* message){xSemaphoreTake(mutex,portMAX_DELAY);if(cmd.generation==generation){w->working.busy=false;snprintf(w->working.message,sizeof(w->working.message),"%s",message);w->working.serial=w->state.serial+1;w->state=w->working;}xSemaphoreGive(mutex);}
void enqueue(Action action,int id=0,unsigned after=0){if(!visible)return;
    // Queue receives a copy; GUI and worker use separate storage for commands.
    auto* local=static_cast<Command*>(heap_caps_calloc(1,sizeof(Command),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT));if(!local)return;
    xSemaphoreTake(mutex,portMAX_DELAY);if(w->state.busy){xSemaphoreGive(mutex);free(local);return;}
    local->action=action;local->id=id;local->after=after;local->generation=generation;
    for(unsigned i=0;i<field_count;++i)snprintf(local->fields[i],sizeof(local->fields[i]),"%s",lv_textarea_get_text(fields[i]));
    for(unsigned i=0;i<2;++i)local->payment[i]=lv_dropdown_get_selected(payments[i]);
    if(xQueueSend(queue,local,0)==pdTRUE){w->state.busy=true;++w->state.serial;snprintf(w->state.message,sizeof(w->state.message),"Aguarde...");}
    xSemaphoreGive(mutex);free(local);
}
void keyboard_event(lv_event_t* e){lv_keyboard_set_textarea(keyboard,lv_event_get_target_obj(e));lv_obj_remove_flag(keyboard,LV_OBJ_FLAG_HIDDEN);}
void row_event(lv_event_t* e){if(w->draw.busy)return;int id=static_cast<int>(reinterpret_cast<intptr_t>(lv_event_get_user_data(e)));if(w->draw.mode==Mode::CustomerSearch){char text[24];snprintf(text,sizeof(text),"%d",id);lv_textarea_set_text(fields[4],text);xSemaphoreTake(mutex,portMAX_DELAY);w->state.mode=Mode::Cart;++w->state.serial;snprintf(w->state.message,sizeof(w->state.message),"Cliente ID %d selecionado; API validará na finalização.",id);xSemaphoreGive(mutex);}
    else if(w->draw.mode==Mode::Search)enqueue(Action::Select,id);else if(w->draw.mode==Mode::History)enqueue(Action::Detail,id);else{char text[48];snprintf(text,sizeof(text),"%d",id);lv_textarea_set_text(fields[0],text);for(unsigned i=0;i<w->draw.size;++i){const auto& item=w->draw.items[i];if(item.id!=id)continue;money::format(text,sizeof(text),item.quantity,3);lv_textarea_set_text(fields[1],text);money::format(text,sizeof(text),item.amount);lv_textarea_set_text(fields[2],text);money::format(text,sizeof(text),item.percent);lv_textarea_set_text(fields[3],text);break;}}}
void click(lv_event_t* e){unsigned i=reinterpret_cast<uintptr_t>(lv_event_get_user_data(e));if(i==7){sales_hide();home_callback();return;}const auto& s=w->draw;
    if(s.mode==Mode::Cart){if(i==6){for(unsigned f=0;f<9;++f)lv_textarea_set_text(fields[f],f==1?"1":"0");}Action actions[]={Action::Add,Action::Remove,Action::Search,Action::Quote,Action::Refresh,Action::History,Action::New};enqueue(actions[i]);}
    else if(s.mode==Mode::Pending){if(i==0)enqueue(Action::Retry);if(i==1)enqueue(Action::Resolve);}
    else if(s.mode==Mode::Review){if(i==0)enqueue(Action::Finish);if(i==1){xSemaphoreTake(mutex,portMAX_DELAY);w->state.mode=Mode::Cart;++w->state.serial;xSemaphoreGive(mutex);}}
    else if(s.mode==Mode::Search||s.mode==Mode::CustomerSearch||s.mode==Mode::History){if(i==0)enqueue(s.mode==Mode::Search?Action::Search:s.mode==Mode::CustomerSearch?Action::CustomerSearch:Action::History,0,s.next);if(i==1){xSemaphoreTake(mutex,portMAX_DELAY);w->state.mode=Mode::Cart;++w->state.serial;xSemaphoreGive(mutex);}if(i==2)enqueue(s.mode==Mode::CustomerSearch?Action::Search:Action::CustomerSearch);if(i==3)enqueue(s.mode==Mode::CustomerSearch?Action::CustomerSearch:Action::Search);}
    else if(s.mode==Mode::Receipt){if(i==0){for(unsigned f=0;f<9;++f)lv_textarea_set_text(fields[f],f==1?"1":"0");enqueue(Action::New);}if(i==1)enqueue(Action::History);if(i==2){xSemaphoreTake(mutex,portMAX_DELAY);w->state.mode=Mode::Cancel;++w->state.serial;xSemaphoreGive(mutex);}}
    else if(s.mode==Mode::Cancel){if(i==0)enqueue(Action::Cancel,s.sale);if(i==1)enqueue(Action::Detail,s.sale);}
}
void render(lv_timer_t*){if(!visible)return;xSemaphoreTake(mutex,portMAX_DELAY);w->draw=w->state;xSemaphoreGive(mutex);auto& s=w->draw;if(s.serial==drawn)return;drawn=s.serial;
    lv_label_set_text(title,s.mode==Mode::Pending?"PDV | Tentativa pendente":s.mode==Mode::History?"PDV | Histórico":s.mode==Mode::CustomerSearch?"PDV | Clientes":s.mode==Mode::Search?"PDV | Produtos":s.mode==Mode::Review?"PDV | Confirmar venda":s.mode==Mode::Receipt?"Comprovante NÃO FISCAL":s.mode==Mode::Cancel?"PDV | Cancelar venda":"Vendas / PDV");lv_label_set_text(notice,s.message);
    if(s.mode==Mode::Cart){
        int64_t gross=0,discount=0;bool valid=true;
        for(unsigned i=0;i<s.size;++i){int64_t line=0;if(!money::line(s.items[i].price,s.items[i].quantity,line)||gross>99999999999999LL-line){valid=false;break;}gross+=line;int64_t cut=s.items[i].amount?s.items[i].amount:money::percent(line,s.items[i].percent);if(cut>line){valid=false;break;}discount+=cut;}
        int64_t amount=0,percent=0;
        if(!money::parse(lv_textarea_get_text(fields[5]),2,amount)||!money::parse(lv_textarea_get_text(fields[6]),2,percent)||percent>10000||(amount&&percent))valid=false;
        if(valid){int64_t cut=amount?amount:money::percent(gross-discount,percent);if(cut>gross-discount)valid=false;else discount+=cut;}
        char subtotal[48],cut[48],total[48],info[240];money::format(subtotal,sizeof(subtotal),gross);money::format(cut,sizeof(cut),discount);money::format(total,sizeof(total),valid?gross-discount:0);
        snprintf(info,sizeof(info),"Prévia: subtotal R$ %s | desconto R$ %s | total R$ %s | API confirma.",subtotal,cut,valid?total:"inválido");lv_label_set_text(preview,info);lv_obj_remove_flag(preview,LV_OBJ_FLAG_HIDDEN);
    }else lv_obj_add_flag(preview,LV_OBJ_FLAG_HIDDEN);
    bool cart=s.mode==Mode::Cart,listing=cart||s.mode==Mode::Search||s.mode==Mode::CustomerSearch||s.mode==Mode::History;
    for(unsigned i=0;i<field_count;++i){bool show=(cart&&i<10)||((s.mode==Mode::Search||s.mode==Mode::CustomerSearch)&&i==9)||(s.mode==Mode::Cancel&&i==10);for(auto* o:{fields[i],labels[i]}){if(show)lv_obj_remove_flag(o,LV_OBJ_FLAG_HIDDEN);else lv_obj_add_flag(o,LV_OBJ_FLAG_HIDDEN);}if(s.busy)lv_obj_add_state(fields[i],LV_STATE_DISABLED);else lv_obj_remove_state(fields[i],LV_STATE_DISABLED);}
    for(auto* p:payments){if(cart)lv_obj_remove_flag(p,LV_OBJ_FLAG_HIDDEN);else lv_obj_add_flag(p,LV_OBJ_FLAG_HIDDEN);if(s.busy)lv_obj_add_state(p,LV_STATE_DISABLED);else lv_obj_remove_state(p,LV_STATE_DISABLED);}
    static Mode previous=Mode::Blocked;if(s.mode!=previous||s.busy)lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);previous=s.mode;if(listing){lv_obj_remove_flag(list,LV_OBJ_FLAG_HIDDEN);lv_obj_add_flag(receipt_panel,LV_OBJ_FLAG_HIDDEN);}else{lv_obj_add_flag(list,LV_OBJ_FLAG_HIDDEN);lv_obj_remove_flag(receipt_panel,LV_OBJ_FLAG_HIDDEN);lv_label_set_text(summary,s.summary);lv_obj_set_height(receipt_panel,s.mode==Mode::Cancel?310:400);}
    for(unsigned i=0;i<8;++i){lv_obj_remove_event_cb(rows[i],row_event);if(listing&&i<(cart?s.size:s.count)){char line[650];if(cart){char price[40],qty[40];money::format(price,sizeof(price),s.items[i].price);money::format(qty,sizeof(qty),s.items[i].quantity,3);snprintf(line,sizeof(line),"ID %d | %s | %s x R$ %s",s.items[i].id,s.items[i].name,qty,price);}else snprintf(line,sizeof(line),"%s",s.rows[i].label);lv_label_set_text(lv_obj_get_child(rows[i],0),line);lv_obj_remove_flag(rows[i],LV_OBJ_FLAG_HIDDEN);lv_obj_add_event_cb(rows[i],row_event,LV_EVENT_CLICKED,reinterpret_cast<void*>(static_cast<intptr_t>(cart?s.items[i].id:s.rows[i].id)));}else lv_obj_add_flag(rows[i],LV_OBJ_FLAG_HIDDEN);}
    const char* names[8]={"","","","","","","","Menu"};
    if(cart){names[0]="Adicionar / editar";names[1]="Remover";names[2]="Pesquisar";names[3]="Calcular venda";names[4]="Atualizar preços";names[5]="Histórico";names[6]="Limpar carrinho";}
    if(s.mode==Mode::Review){names[0]="Finalizar venda";names[1]="Voltar";}
    if(s.mode==Mode::Pending){names[0]="Reenviar";names[1]="Resolver tentativa";}
    if(s.mode==Mode::History||s.mode==Mode::Search||s.mode==Mode::CustomerSearch){names[0]="Próxima";names[1]="Voltar";if(s.mode!=Mode::History){names[2]=s.mode==Mode::CustomerSearch?"Buscar produto":"Buscar cliente";names[3]="Pesquisar";}}
    if(s.mode==Mode::Receipt){names[0]=s.pending?"Resolver tentativa":"Nova venda";names[1]="Histórico";if(!s.canceled&&permitted(w->permissions,"sales.cancel"))names[2]="Cancelar venda";}
    if(s.mode==Mode::Cancel){names[0]="Confirmar cancel.";names[1]="Voltar";}
    for(unsigned i=0;i<8;++i){lv_label_set_text(lv_obj_get_child(buttons[i],0),names[i]);lv_obj_center(lv_obj_get_child(buttons[i],0));if(*names[i])lv_obj_remove_flag(buttons[i],LV_OBJ_FLAG_HIDDEN);else lv_obj_add_flag(buttons[i],LV_OBJ_FLAG_HIDDEN);if((s.busy&&i!=7)||(i==0&&(s.mode==Mode::Search||s.mode==Mode::CustomerSearch||s.mode==Mode::History)&&!s.next))lv_obj_add_state(buttons[i],LV_STATE_DISABLED);else lv_obj_remove_state(buttons[i],LV_STATE_DISABLED);}
}
cJSON* cart_json(const Command& cmd,bool payment){auto* body=cJSON_CreateObject();auto* items=cJSON_AddArrayToObject(body,"items");char num[48];for(unsigned i=0;i<w->working.size;++i){auto& item=w->working.items[i];auto* j=cJSON_CreateObject();cJSON_AddItemToArray(items,j);cJSON_AddNumberToObject(j,"product_id",item.id);cJSON_AddNumberToObject(j,"product_version",item.version);money::format(num,sizeof(num),item.quantity,3);cJSON_AddStringToObject(j,"quantity",num);money::format(num,sizeof(num),item.price);cJSON_AddStringToObject(j,"expected_unit_price",num);money::format(num,sizeof(num),item.amount);cJSON_AddStringToObject(j,"discount_amount",num);money::format(num,sizeof(num),item.percent);cJSON_AddStringToObject(j,"discount_percent",num);}
    int64_t parsed=0;if(!money::parse(cmd.fields[4],0,parsed)||parsed>2147483647){cJSON_Delete(body);return nullptr;}if(parsed)cJSON_AddNumberToObject(body,"customer_id",parsed);
    for(unsigned i=5;i<=6;++i){if(!money::parse(cmd.fields[i],2,parsed)||(i==6&&parsed>10000)){cJSON_Delete(body);return nullptr;}money::format(num,sizeof(num),parsed);cJSON_AddStringToObject(body,i==5?"discount_amount":"discount_percent",num);}
    if(payment){auto* pays=cJSON_AddArrayToObject(body,"payments");for(unsigned i=0;i<2;++i){if(!money::parse(cmd.fields[7+i],2,parsed)){cJSON_Delete(body);return nullptr;}if(parsed){auto* p=cJSON_CreateObject();cJSON_AddItemToArray(pays,p);cJSON_AddStringToObject(p,"method",methods[cmd.payment[i]<6?cmd.payment[i]:0]);money::format(num,sizeof(num),parsed);cJSON_AddStringToObject(p,"amount",num);}}}return body;
}
void receipt(cJSON* data){auto& s=w->working;s.sale=integer(data,"id");s.canceled=!strcmp(value(data,"status"),"canceled");s.mode=Mode::Receipt;snprintf(s.summary,sizeof(s.summary),"Venda %d | %s | %s\nCliente ID %d | Operador ID %d\nSubtotal R$ %s | Desconto R$ %s\nTotal R$ %s | Recebido R$ %s | Troco R$ %s\n\n",s.sale,s.canceled?"CANCELADA":"Concluída",value(data,"created_at"),integer(data,"customer_id"),integer(data,"operator_id"),value(data,"subtotal"),value(data,"discount"),value(data,"total"),value(data,"tendered"),value(data,"change"));auto append=[&](const char* line){size_t n=strlen(s.summary);snprintf(s.summary+n,sizeof(s.summary)-n,"%s",line);};cJSON* item;auto* items=cJSON_GetObjectItemCaseSensitive(data,"items");cJSON_ArrayForEach(item,items){char line[650];snprintf(line,sizeof(line),"%s | %s x R$ %s = R$ %s\n",value(item,"name"),value(item,"quantity"),value(item,"unit_price"),value(item,"subtotal"));append(line);}auto* pays=cJSON_GetObjectItemCaseSensitive(data,"payments");cJSON_ArrayForEach(item,pays){char line[160];snprintf(line,sizeof(line),"%s R$ %s | %s\n",value(item,"method"),value(item,"amount"),value(item,"status"));append(line);}if(s.canceled){append("\nMotivo: ");append(value(data,"cancel_reason"));append("\n");}append("\nPagamentos declarados pelo operador. Documento NÃO FISCAL.\nCancelamento gerencial não confirma estorno externo.");}
bool decode_product(cJSON* data,Item& item){item.id=integer(data,"id");item.version=integer(data,"version");snprintf(item.name,sizeof(item.name),"%s",value(data,"name"));return item.id>0&&item.version>0&&cJSON_IsTrue(cJSON_GetObjectItemCaseSensitive(data,"active"))&&money::parse(value(data,"sale_price"),2,item.price);}
const char* failure(int code,cJSON* data){auto* error=cJSON_GetObjectItemCaseSensitive(data,"error");const char* m=value(error,"message");if(*m)return m;return code<=0?"Sem resposta da API. Confira Wi-Fi, hora e servidor.":"Operação recusada pela API. Atualize os dados e confira os campos.";}
} // namespace
void sales_create(lv_display_t* display,void(*home)()){
    void* mem=heap_caps_calloc(1,sizeof(Workspace),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);if(!mem){ESP_LOGE("sales","PSRAM indisponível");return;}w=new(mem)Workspace{};mutex=xSemaphoreCreateMutex();auto* queue_memory=static_cast<uint8_t*>(heap_caps_malloc(sizeof(Command),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT));static StaticQueue_t queue_control;queue=xQueueCreateStatic(1,sizeof(Command),queue_memory,&queue_control);home_callback=home;
    root=lv_obj_create(lv_display_get_screen_active(display));lv_obj_set_size(root,1280,720);lv_obj_set_style_pad_all(root,10,0);lv_obj_remove_flag(root,LV_OBJ_FLAG_SCROLLABLE);lv_obj_set_style_text_font(root,&erp_font_pt_20,0);
    title=lv_label_create(root);lv_obj_set_pos(title,8,0);lv_obj_set_style_text_font(title,&erp_font_pt_28,0);notice=lv_label_create(root);lv_obj_set_pos(notice,8,40);lv_obj_set_width(notice,1200);lv_label_set_long_mode(notice,LV_LABEL_LONG_DOT);preview=lv_label_create(root);lv_obj_set_pos(preview,8,74);lv_obj_set_width(preview,1200);
    list=lv_obj_create(root);lv_obj_set_pos(list,8,100);lv_obj_set_size(list,1220,210);for(unsigned i=0;i<8;++i){rows[i]=lv_button_create(list);lv_obj_set_pos(rows[i],0,i*45);lv_obj_set_size(rows[i],1170,42);auto* l=lv_label_create(rows[i]);lv_obj_set_width(l,1135);lv_label_set_long_mode(l,LV_LABEL_LONG_DOT);lv_obj_center(l);}
    receipt_panel=lv_obj_create(root);lv_obj_set_pos(receipt_panel,8,100);lv_obj_set_size(receipt_panel,1220,400);summary=lv_label_create(receipt_panel);lv_obj_set_width(summary,1170);lv_label_set_long_mode(summary,LV_LABEL_LONG_WRAP);
    for(unsigned i=0;i<field_count;++i){int x=8+(i%6)*204,y=320+(i/6)*82;if(i==10){x=8;y=440;}labels[i]=lv_label_create(root);lv_obj_set_pos(labels[i],x,y);lv_label_set_text(labels[i],captions[i]);lv_obj_set_width(labels[i],194);lv_label_set_long_mode(labels[i],LV_LABEL_LONG_DOT);fields[i]=lv_textarea_create(root);lv_obj_set_pos(fields[i],x,y+28);lv_obj_set_size(fields[i],i==10?1210:194,46);lv_textarea_set_one_line(fields[i],true);lv_textarea_set_max_length(fields[i],i==9?120:i==10?240:24);lv_textarea_set_text(fields[i],i==1?"1":i<9?"0":"");lv_obj_add_event_cb(fields[i],keyboard_event,LV_EVENT_CLICKED,nullptr);if(i==5||i==6)lv_obj_add_event_cb(fields[i],[](lv_event_t*){xSemaphoreTake(mutex,portMAX_DELAY);++w->state.serial;xSemaphoreGive(mutex);},LV_EVENT_VALUE_CHANGED,nullptr);}
    for(unsigned i=0;i<2;++i){payments[i]=lv_dropdown_create(root);lv_obj_set_pos(payments[i],8+i*235,492);lv_obj_set_size(payments[i],224,42);lv_dropdown_set_options(payments[i],"Dinheiro\nPix\nDébito\nCrédito\nTransferência\nOutro");lv_dropdown_set_selected(payments[i],i);}
    for(unsigned i=0;i<8;++i){buttons[i]=lv_button_create(root);lv_obj_set_pos(buttons[i],8+(i%4)*306,542+(i/4)*58);lv_obj_set_size(buttons[i],294,50);lv_label_create(buttons[i]);lv_obj_add_event_cb(buttons[i],click,LV_EVENT_CLICKED,reinterpret_cast<void*>(static_cast<uintptr_t>(i)));}
    keyboard=lv_keyboard_create(root);lv_obj_set_pos(keyboard,8,420);lv_obj_set_size(keyboard,1220,270);for(auto code:{LV_EVENT_READY,LV_EVENT_CANCEL})lv_obj_add_event_cb(keyboard,[](lv_event_t*){lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);},code,nullptr);lv_obj_add_flag(keyboard,LV_OBJ_FLAG_HIDDEN);lv_obj_add_flag(root,LV_OBJ_FLAG_HIDDEN);lv_timer_create(render,100,nullptr);
}
void sales_hide(bool clear){if(!w)return;visible=false;++generation;xQueueReset(queue);lv_obj_add_flag(root,LV_OBJ_FLAG_HIDDEN);if(clear){xSemaphoreTake(mutex,portMAX_DELAY);memset(&w->state,0,sizeof(w->state));xSemaphoreGive(mutex);for(unsigned i=0;i<field_count;++i)lv_textarea_set_text(fields[i],i==1?"1":i<9?"0":"");lv_label_set_text(summary,"");lv_label_set_text(notice,"");lv_label_set_text(preview,"");for(auto* row:rows)lv_label_set_text(lv_obj_get_child(row,0),"");memset(&w->draw,0,sizeof(w->draw));}}
void sales_open(const char* permissions,bool light){if(!w)return;snprintf(w->permissions,sizeof(w->permissions),"%s",permissions);drawn=0;auto fg=lv_color_hex(light?0x0f172a:0xf8fafc),bg=lv_color_hex(light?0xe2e8f0:0x334155);lv_obj_set_style_bg_color(root,lv_color_hex(light?0xf1f5f9:0x111827),0);lv_obj_set_style_text_color(root,fg,0);lv_obj_set_style_bg_color(list,lv_color_hex(light?0xffffff:0x1e293b),0);lv_obj_set_style_bg_color(receipt_panel,lv_color_hex(light?0xffffff:0x1e293b),0);
    for(auto* o:fields){lv_obj_set_style_bg_color(o,bg,0);lv_obj_set_style_text_color(o,fg,0);}for(auto* o:rows){lv_obj_set_style_bg_color(o,bg,0);lv_obj_set_style_text_color(o,fg,0);}for(auto* o:buttons){lv_obj_set_style_bg_color(o,bg,0);lv_obj_set_style_text_color(o,fg,0);}for(auto* o:payments){lv_obj_set_style_bg_color(o,bg,0);lv_obj_set_style_text_color(o,fg,0);auto* l=lv_dropdown_get_list(o);lv_obj_set_style_bg_color(l,bg,0);lv_obj_set_style_text_color(l,fg,0);}lv_obj_set_style_bg_color(keyboard,bg,LV_PART_ITEMS);lv_obj_set_style_text_color(keyboard,fg,LV_PART_ITEMS);
    visible=true;lv_obj_remove_flag(root,LV_OBJ_FLAG_HIDDEN);enqueue(Action::Init);render(nullptr);
}
bool sales_handle_next(const char* permissions,bool online,ProductTransport transport,SaleJournal journal){if(!w)return false;
    // Command is large (UTF-8 forms); keep it on PSRAM, never the worker stack.
    auto* cmd=&w->command;if(xQueueReceive(queue,cmd,0)!=pdTRUE)return false;if(cmd->generation!=generation)return true;
    xSemaphoreTake(mutex,portMAX_DELAY);w->working=w->state;xSemaphoreGive(mutex);
    auto complete=[&](const char* text){publish(*cmd,text);return true;};
    if(!online)return complete("Venda exige conexão com a API. Carrinho não foi enviado.");
    auto call=[&](const char* method,const char* path,const char* body){memset(w->response,0,sizeof(w->response));return transport(method,path,body,w->response,sizeof(w->response));};
    if(cmd->action==Action::Init){int code=call("GET","/api/v1/auth/me",nullptr);auto* j=cJSON_Parse(w->response);int user=integer(j,"id");cJSON_Delete(j);if(code!=200||!user)return complete("Não foi possível confirmar o operador.");if(w->working.user&&w->working.user!=user)memset(&w->working,0,sizeof(w->working));w->working.user=user;int loaded=journal("load",user,w->pending,sizeof(w->pending));w->working.pending=loaded!=0;w->working.mode=loaded==1?Mode::Pending:loaded<0?Mode::Blocked:Mode::Cart;snprintf(w->working.summary,sizeof(w->working.summary),"Tentativa registrada no microSD. Reenviar usa a mesma chave. Resolver confirma o resultado ou encerra a tentativa na API antes de permitir nova venda.");return complete(loaded<0?"Pendência protegida: use o operador/API originais e confira o microSD.":loaded==1?"Venda pendente recuperada. Resolva antes de iniciar outra.":"Online. Informe produto/quantidade; preços serão confirmados pela API.");}
    if(w->working.pending&&cmd->action!=Action::Retry&&cmd->action!=Action::Resolve)return complete("Resolva a venda pendente antes de continuar.");
    bool reading=cmd->action==Action::History||cmd->action==Action::Detail;
    const char* permission=cmd->action==Action::Cancel?"sales.cancel":reading?"sales.read":"sales.create";
    if(!permitted(permissions,permission))return complete("Seu perfil não permite esta operação.");
    if(cmd->action==Action::New){w->working.size=0;w->working.mode=Mode::Cart;w->payload[0]=0;return complete("Carrinho limpo. Confira cliente, descontos e pagamentos para a nova venda.");}
    if(cmd->action==Action::Add||cmd->action==Action::Select||cmd->action==Action::Remove){int64_t id=cmd->id,qty=1000,amount=0,percent=0;if(cmd->action!=Action::Select&&(!money::parse(cmd->fields[0],0,id)||id<=0||id>2147483647))return complete("Informe ID inteiro do produto.");if(cmd->action==Action::Add&&(!money::parse(cmd->fields[1],3,qty)||qty<=0||!money::parse(cmd->fields[2],2,amount)||!money::parse(cmd->fields[3],2,percent)||percent>10000||(amount&&percent)))return complete("Quantidade inválida ou desconto: escolha valor OU percentual.");unsigned index=0;while(index<w->working.size&&w->working.items[index].id!=id)++index;
        if(cmd->action==Action::Remove){if(index==w->working.size)return complete("Produto não está no carrinho.");for(unsigned i=index+1;i<w->working.size;++i)w->working.items[i-1]=w->working.items[i];--w->working.size;return complete("Item removido.");}
        if(index>=8){return complete("Máximo de 8 produtos diferentes por venda nesta tela.");}
        char path[80];snprintf(path,sizeof(path),"/api/v1/products/%lld",static_cast<long long>(id));int code=call("GET",path,nullptr);auto* j=cJSON_Parse(w->response);Item item{};bool ok=code==200&&decode_product(j,item);cJSON_Delete(j);if(!ok)return complete("Produto indisponível. Confira cadastro ativo e conexão.");item.quantity=qty;item.amount=amount;item.percent=percent;w->working.items[index]=item;if(index==w->working.size)++w->working.size;w->working.mode=Mode::Cart;return complete("Item atualizado. Calcular venda confirma totais, estoque e pagamentos.");}
    if(cmd->action==Action::Refresh){for(unsigned i=0;i<w->working.size;++i){char path[80];snprintf(path,sizeof(path),"/api/v1/products/%d",w->working.items[i].id);int code=call("GET",path,nullptr);auto* j=cJSON_Parse(w->response);bool ok=code==200&&decode_product(j,w->working.items[i]);cJSON_Delete(j);if(!ok)return complete("Produto indisponível. Remova-o ou confira cadastro.");}w->working.mode=Mode::Cart;return complete("Preços/cadastros atualizados. Revise o carrinho antes de confirmar.");}
    char path[160];const char* method="GET";char* raw=nullptr;
    if(cmd->action==Action::Quote){auto* body=cart_json(*cmd,false);if(!body)return complete("Confira cliente, descontos e valores com até 2 casas decimais.");raw=cJSON_PrintUnformatted(body);cJSON_Delete(body);snprintf(path,sizeof(path),"/api/v1/sales/quote");method="POST";}
    else if(cmd->action==Action::Finish){if(w->working.mode!=Mode::Review||!w->payload[0])return complete("Calcule e revise a venda antes de finalizar.");uint8_t bytes[16];esp_fill_random(bytes,sizeof(bytes));char key[33];for(unsigned i=0;i<16;++i)snprintf(key+2*i,3,"%02x",bytes[i]);auto* body=cJSON_Parse(w->payload);cJSON_AddStringToObject(body,"idempotency_key",key);raw=cJSON_PrintUnformatted(body);cJSON_Delete(body);if(!raw||strlen(raw)>=sizeof(w->pending)){cJSON_free(raw);return complete("Carrinho excede limite de armazenamento.");}snprintf(w->pending,sizeof(w->pending),"%s",raw);cJSON_free(raw);raw=nullptr;if(journal("save",w->working.user,w->pending,sizeof(w->pending))!=1)return complete("Falha ao registrar tentativa no microSD. Venda não enviada.");w->working.pending=true;w->working.mode=Mode::Pending;snprintf(path,sizeof(path),"/api/v1/sales");method="POST";}
    else if(cmd->action==Action::Retry){snprintf(path,sizeof(path),"/api/v1/sales");method="POST";}
    else if(cmd->action==Action::Resolve){auto* body=cJSON_Parse(w->pending);const char* key=value(body,"idempotency_key");if(strlen(key)<16||strlen(key)>64){cJSON_Delete(body);return complete("Registro pendente inválido. Preserve o microSD para recuperação.");}snprintf(path,sizeof(path),"/api/v1/sales/requests/%s/resolve",key);cJSON_Delete(body);method="POST";}
    else if(cmd->action==Action::History)snprintf(path,sizeof(path),"/api/v1/sales?after_id=%u&limit=8",cmd->after);
    else if(cmd->action==Action::Detail)snprintf(path,sizeof(path),"/api/v1/sales/%d",cmd->id);
    else if(cmd->action==Action::Cancel){snprintf(path,sizeof(path),"/api/v1/sales/%d/cancel",cmd->id);auto* body=cJSON_CreateObject();cJSON_AddStringToObject(body,"reason",cmd->fields[10]);raw=cJSON_PrintUnformatted(body);cJSON_Delete(body);method="POST";}
    else if(cmd->action==Action::CustomerSearch){if(!permitted(permissions,"customers.read"))return complete("Seu perfil não permite consultar clientes.");auto* b=cJSON_CreateObject();cJSON_AddStringToObject(b,"q",cmd->fields[9]);cJSON_AddNumberToObject(b,"after_id",cmd->after);cJSON_AddNumberToObject(b,"limit",8);raw=cJSON_PrintUnformatted(b);cJSON_Delete(b);int code=call("POST","/api/v1/customers/search",raw);cJSON_free(raw);auto* j=cJSON_Parse(w->response);if(code==200){w->working.mode=Mode::CustomerSearch;w->working.count=0;w->working.next=integer(j,"next_id");cJSON* p;auto* items=cJSON_GetObjectItemCaseSensitive(j,"items");cJSON_ArrayForEach(p,items){if(w->working.count>=8)break;auto& row=w->working.rows[w->working.count++];row.id=integer(p,"id");snprintf(row.label,sizeof(row.label),"ID %d | %s",row.id,value(p,"name"));}}std::string msg=code==200?"Toque no cliente para selecionar. ID 0 permite venda sem identificação.":failure(code,j);cJSON_Delete(j);return complete(msg.c_str());}
    else {std::string q;const unsigned char* c=reinterpret_cast<const unsigned char*>(cmd->fields[9]);for(;*c;++c){char encoded[4];snprintf(encoded,sizeof(encoded),"%%%02X",*c);q+=encoded;}std::string full="/api/v1/products?q="+q+"&limit=8&after_id="+std::to_string(cmd->after);int code=call("GET",full.c_str(),nullptr);auto* j=cJSON_Parse(w->response);if(code==200){w->working.mode=Mode::Search;w->working.count=0;w->working.next=integer(j,"next_id");cJSON* p;auto* items=cJSON_GetObjectItemCaseSensitive(j,"items");cJSON_ArrayForEach(p,items){if(w->working.count>=8)break;auto& row=w->working.rows[w->working.count++];row.id=integer(p,"id");snprintf(row.label,sizeof(row.label),"ID %d | %s | R$ %s",row.id,value(p,"name"),value(p,"sale_price"));}}std::string msg=code==200?"Toque no produto para adicionar uma unidade.":failure(code,j);cJSON_Delete(j);return complete(msg.c_str());}
    const char* body=(cmd->action==Action::Finish||cmd->action==Action::Retry)?w->pending:raw;int code=call(method,path,body);cJSON_free(raw);auto* data=cJSON_Parse(w->response);std::string message;
    if(code<200||code>=300){message=failure(code,data);if(w->working.pending){w->working.mode=Mode::Pending;snprintf(w->working.summary,sizeof(w->working.summary),"Resultado ainda não confirmado. Reenviar repete a MESMA tentativa; Resolver confirma ou encerra a tentativa na API. Não gere uma nova venda para substituir esta pendência.");}}
    else if(cmd->action==Action::Quote){auto* final_body=cart_json(*cmd,true);char* payload=final_body?cJSON_PrintUnformatted(final_body):nullptr;cJSON_Delete(final_body);if(!payload||strlen(payload)>=sizeof(w->payload)){message="Confira os pagamentos e o limite do carrinho.";}else{snprintf(w->payload,sizeof(w->payload),"%s",payload);w->working.mode=Mode::Review;snprintf(w->working.summary,sizeof(w->working.summary),"Subtotal R$ %s\nDescontos R$ %s\nTOTAL R$ %s\n\nPagamento 1: %s R$ %s\nPagamento 2: %s R$ %s\nCliente ID: %s\n\nPagamentos declarados pelo operador.\nConfirme apenas após conferir os valores e receber o pagamento.\nPreço e estoque serão novamente validados na finalização.",value(data,"subtotal"),value(data,"discount"),value(data,"total"),methods[cmd->payment[0]],cmd->fields[7],methods[cmd->payment[1]],cmd->fields[8],cmd->fields[4]);message="Revise. Finalizar grava venda, pagamentos e estoque em uma transação.";}cJSON_free(payload);}
    else if(cmd->action==Action::History){w->working.mode=Mode::History;w->working.count=0;w->working.next=integer(data,"next_id");cJSON* p;auto* items=cJSON_GetObjectItemCaseSensitive(data,"items");cJSON_ArrayForEach(p,items){if(w->working.count>=8)break;auto& row=w->working.rows[w->working.count++];row.id=integer(p,"id");snprintf(row.label,sizeof(row.label),"Venda %d | %s | R$ %s | %s",row.id,value(p,"created_at"),value(p,"total"),value(p,"status"));}message="Toque para consultar os valores originais da venda.";}
    else if(cmd->action==Action::Resolve&&!strcmp(value(data,"state"),"abandoned")){if(journal("clear",w->working.user,w->pending,sizeof(w->pending))==1){w->working.pending=false;w->pending[0]=0;w->working.mode=Mode::Cart;message="Tentativa encerrada na API. Atualize e revise o carrinho antes de tentar novamente.";}else message="Tentativa encerrada, mas falhou a limpeza do cartão. Resolva novamente.";}
    else{cJSON* sale=cmd->action==Action::Resolve?cJSON_GetObjectItemCaseSensitive(data,"sale"):data;if(!integer(sale,"id")){message="Resposta da API inválida; preserve a tentativa pendente.";}else{receipt(sale);if(cmd->action==Action::Finish||cmd->action==Action::Retry||cmd->action==Action::Resolve){w->working.size=0;w->payload[0]=0;}if(w->working.pending){if(journal("clear",w->working.user,w->pending,sizeof(w->pending))==1){w->working.pending=false;w->pending[0]=0;}else w->working.mode=Mode::Pending;}message=w->working.pending?"Venda confirmada; resolva novamente para limpar o registro no cartão.":w->working.canceled?"Cancelamento gerencial confirmado. Estoque reposto uma única vez.":"Venda confirmada no servidor. Comprovante não fiscal.";}}
    cJSON_Delete(data);return complete(message.c_str());
}
} // namespace tab5
