"""Add cash and financial ledgers without rewriting historical sales."""
from alembic import op
revision='006_cash'
down_revision='005_inventory'
branch_labels=None
depends_on=None
# Use explicit copies of the release schema: never import evolving ORM in migration.
def upgrade():
    import sqlalchemy as sa
    op.create_table('cash_sessions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('device_id',sa.String(80),nullable=False),sa.Column('status',sa.String(16),nullable=False),sa.Column('opening',sa.Numeric(14,2),nullable=False),sa.Column('counted',sa.Numeric(14,2)),sa.Column('note',sa.String(240),nullable=False),sa.Column('close_reason',sa.String(240)),sa.Column('snapshot',sa.Text()),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('closed_at',sa.DateTime()),sa.CheckConstraint("status IN ('open','closed')",name='ck_cash_status'),sa.CheckConstraint('opening >= 0 AND counted >= 0',name='ck_cash_amounts'))
    op.create_index('ix_cash_sessions_user_id','cash_sessions',['user_id'])
    op.create_table('financial_categories',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('kind',sa.String(16),nullable=False),sa.Column('name',sa.String(80),nullable=False),sa.UniqueConstraint('kind','name',name='uq_financial_category'),sa.CheckConstraint("kind IN ('receivable','payable')",name='ck_financial_category_kind'))
    op.create_table('financial_accounts',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('kind',sa.String(16),nullable=False),sa.Column('category_id',sa.Integer(),sa.ForeignKey('financial_categories.id'),nullable=False),sa.Column('contact_id',sa.Integer(),sa.ForeignKey('contacts.id')),sa.Column('description',sa.String(240),nullable=False),sa.Column('due_date',sa.Date(),nullable=False),sa.Column('amount',sa.Numeric(14,2),nullable=False),sa.Column('paid',sa.Numeric(14,2),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.CheckConstraint("kind IN ('receivable','payable')",name='ck_financial_account_kind'),sa.CheckConstraint('amount > 0 AND paid >= 0 AND paid <= amount',name='ck_financial_account_amount'))
    op.create_index('ix_financial_accounts_kind','financial_accounts',['kind']);op.create_index('ix_financial_accounts_due_date','financial_accounts',['due_date'])
    op.create_table('financial_settlements',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('account_id',sa.Integer(),sa.ForeignKey('financial_accounts.id'),nullable=False),sa.Column('cash_session_id',sa.Integer(),sa.ForeignKey('cash_sessions.id'),nullable=False),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('amount',sa.Numeric(14,2),nullable=False),sa.Column('method',sa.String(24),nullable=False),sa.Column('reason',sa.String(240),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.CheckConstraint('amount > 0',name='ck_financial_settlement_amount'))
    op.create_index('ix_financial_settlements_account_id','financial_settlements',['account_id'])
    op.create_table('cash_movements',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('cash_session_id',sa.Integer(),sa.ForeignKey('cash_sessions.id'),nullable=False),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('sale_id',sa.Integer(),sa.ForeignKey('sales.id')),sa.Column('settlement_id',sa.Integer(),sa.ForeignKey('financial_settlements.id')),sa.Column('kind',sa.String(24),nullable=False),sa.Column('method',sa.String(24),nullable=False),sa.Column('amount',sa.Numeric(14,2),nullable=False),sa.Column('reason',sa.String(240),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False))
    op.create_index('ix_cash_movements_cash_session_id','cash_movements',['cash_session_id']);op.create_index('ix_cash_movements_sale_id','cash_movements',['sale_id'])
    op.create_table('finance_requests',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('device_id',sa.String(80),nullable=False),sa.Column('idempotency_key',sa.String(64),nullable=False),sa.Column('request_hash',sa.String(64),nullable=False),sa.Column('state',sa.String(16),nullable=False),sa.Column('operation',sa.String(32),nullable=False),sa.Column('result',sa.Text()),sa.Column('created_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('user_id','device_id','idempotency_key',name='uq_finance_request'),sa.CheckConstraint("state IN ('completed','abandoned')",name='ck_finance_request_state'))

def downgrade():
    for table in ('finance_requests','cash_movements','financial_settlements','financial_accounts','financial_categories','cash_sessions'):op.drop_table(table)
